apiVersion: v1
kind: Secret
metadata:
    name: bws-secret
stringData:
    token: ENC[AES256_GCM,data:Jc60lwygd+mHrTPP+yb/9EYKngPttCxxw5hhYusM,iv:AUU35C6TVx6Hg/alMo2Tuguu5CDVk9/6P2///mfiAb8=,tag:p0XFzHSpfk5Owh26oHR7LQ==,type:str]
    ORG_ID: ENC[AES256_GCM,data:Xb3WW4VzojUWGRHpEhocxJO53677EqJA+cC9D2tB,iv:urEHs+axgYA1GkNRcgx9aXnL6tsgaxN6TUSMYZKUt1Y=,tag:UwH9BvQAJyYxdHMb7cIGbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdmM4YzlKNDJmK0RnR2ti
            MU1pSVgzbm1rMnpkL3U5QzFmSjUwU2phNTJZCkpOZ01pdlhXOVI1ZWhMcEYwdlNH
            VE9LeFJRMEI3RkxHSDJJdkRMY0ljK0kKLS0tIHh0T1lRWFh6dndnUVhNcGNsMU1P
            amtFM29YRVRpR2ZhUDZUWDVXcEJzb1UKegaAX4YicAy3q8AP6cE1azQfdHCPybym
            p2Ao/T7Pu1ffRcl5tQoLc9RbXnqyoIu28u66MNeVXKnB7KEmtts+lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-24T13:06:08Z"
    mac: ENC[AES256_GCM,data:0wOJVmqWdsZkkCtvpI7EKgQLFTifj1MdT1fVe9hFU8Q9qeDh987GCgf6LULrwt+jWFSuNwgMQVUiorPkghwoq6bSKsSZ+jMDrDI/adumd446gUr8NGrHChUMUC25e5tX5zq6kfolGXWHUd1JhLgflFrmulu5AUz5MUtWAuwgWSo=,iv:8iWQkVLGqjm9eWuFScMPoiNIvR1tzKedurywBxeJKdc=,tag:PEC5vmBchgBa1C+u6DHmGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
