---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app emhass
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      emhass:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/davidusb-geek/emhass
              tag: "v0.13.3"
            env:
              TZ: Australia/Sydney
              UV_CACHE_DIR: /emhass/.cache/uv
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        controller: emhass
        ports:
          http:
            port: &port 5000
    
    route:
      app:
        hostnames:
          - emhass.narden.au
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config-cache:
        type: emptyDir
        globalMounts:
          - path: /app/.cache/uv
      config-share:
        type: emptyDir
        globalMounts:
          - path: /share
      options-secret:
        type: secret
        name: emhass-secret
        globalMounts:
          - path: /app/secrets_emhass.yaml
            subPath: secrets_emhass.yaml
      data:
        enabled: true
        existingClaim: emhass-data
        globalMounts:
          - path: /emhass