---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot-network
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot-network",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.21",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "172.20.21.0/24"}
            ]
          }
        }
      ]
    }
