apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:pWLea/bsWzdLTIi2rx6cY20bWczzk1F9WyJboyKgcmcTgo2KGjKvaKI=,iv:fjh05mBDr93hDoQpmvhYA91qlCG+ipHSB8bR+EP8JSc=,tag:IdgaJqMv84vSf2awG4uh8w==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:nA1dIly5j0HmoCq5btn8jLxwhWZdAJqLzYPf+z3S,iv:oP6i1G2Tx2vNIRlMJgadjFDR3RIo05VmvCWYbLD14ug=,tag:Bak/ecvYGBhmaN5ArWDPuQ==,type:str]
    BW_HOST: ENC[AES256_GCM,data:s8v0hxhQTiTu3uQpBgrW,iv:YsW3Tk5dbWHVyJQyUhVdBMWE06y0PsvtGMVOS7b1Rk8=,tag:gfpFVrBh1m+eOg6FMb2DEw==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:SVrOrTisPmYfHDdCmSdXBs2+2tQ=,iv:sh0BFaxqiGGTT0yF3LV2R/aM7bSiJZs7x8gfkcVH55k=,tag:5GPP9DRzXRZo/yiWY6HewQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRy9Lbm9BbGMvNWtlNE96
            b1FwSW91eHBMV1lCZ2s2dG9nWEFQc1VMdEZVCmdZUjMvOWMvNnpSRjNEdVFRek5Q
            MXhHY25WV09mNXFkVUFKbjdNc2FTVlEKLS0tIG5iTGNselFKeHZPYjIyMXh2SS9J
            TzZUTnh1b2I3ZXhmWjlST3hoS01ub1EKu2wXZj5d2Zf3cwW/Alu4DI5JY3P1Gw1n
            2KeBFJCLzN4Mh3zx1vAfALPxHmNwgqAVPCsV0mfYi9Ovpnp1aMoqvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T10:06:53Z"
    mac: ENC[AES256_GCM,data:1WIVBLhS5Batwqy30pPXeNrhhdnSZfjcP5wYJyjtmj25NudKx9kMK+1ScDZOzhoKBT0iEC6iVF3WFAj89JEXUHc/enAvCRQKW2zkHxJ8UkZkuNYJQYmQnxaOfCx+77uGDzlxi8gKvybgPoB63nGBCv3H9brwGJCn/4jql3DrYLk=,iv:2/Lajj1Wqi0qp0BQ7n4dkepuO1RpwKQW544icK1l7EQ=,tag:vis7UWjHtA1pVDhs/Eb2IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
