apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
    namespace: kube-system
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:V/0NhO8Rdikug6PWX9uspgsFbF1bfHYPLJXIMvXy09KGwpHAluBbVmA=,iv:tyKJQI66YoMs1YOnVlTQggxYPdZC9K4blJRktakNOWw=,tag:pfpJRFm1ompQU7hE+BC2Wg==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:7MDAREG8GTTAhN1yME0fnyEnBxQ+Tjmkof8vPTUy,iv:6/ALlkyIYOSbhFCdx+b8Bj3GRUHyolNBcZslj4gpUPk=,tag:YunLJJVE53KujI3Fsgh9aQ==,type:str]
    BW_HOST: ENC[AES256_GCM,data:LeMuLzBdFEEpC32ajHPu,iv:+WGXxDdoJMPumtTultluwJLPHOAEuyGVGdUMbyUOLyY=,tag:xF6vQCxl1MNfxe0f5VGvgg==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:yMbLw41vllrM5ZUtu6sbL8CaxVQ=,iv:EQheBSdrayEm9W5UWM3zWAGrLHstY7BfKTa/gH9aYT4=,tag:AvoErSlGnm1MysXEfdCiGQ==,type:str]
    VC_PASSWORD: ENC[AES256_GCM,data:kuVUy+QX+C3hjjZT1UI1IMNwJ9O27cjtBhfsPsbuDMsnIDIo9+4Wdhfwd8SMUdXgkzRN25t/UVn89fgmRkU7OSRSEl6BU4lQZ0vkhxbb5b+kkKw6pAZd+yGty9gw3CzWcgzc+I3Y9tDnU25DRH/eT4qi3F2U07v3zBC/F/pJ1OKCPpgSEeE9IxUnSwmvUuqLZkWmYWW8/i9FzaPCuDINRcjM1oWh+TAYbl5OzRYp/MRBDs90ri8qD2MBa5kILC6PldFEKzUEpnfmz65XS2HM8tKM9D4W2Rk11sS8Lp2oP5H6UWstKAZPkSKWx7hHepcnQqWE3MeVhpXCI0dkKapWyh6IIHUEfXoQy9T143ZhkzNk7Eph1wJh,iv:vIqVl7AHwO0cDSMQcT5wNvduSYNxAfo85qJE8BZcO6Q=,tag:j0V/97ADCxgfjuZDvPqSLQ==,type:str]
    DEBUG: ENC[AES256_GCM,data:QQPgQkUNzus8JlGRu6caBQfv/CGfdbmZkgtJFrQQykbkFz1DuR64aZXF+w/YgCK2tvbOcdBuEyOF8g/YGjsmPr2trhzKjSNhpdhR4Swk7BvmzE3kY/BlIcZwxBil/4vjEi80XnNf/XcOYIPXOdgrZnO3hQjRq0lSd1gd214Y3cC1/bxhWbdFAYRSE2DvfJNWv6f7c7ISc3DdUTJKUdJoU8WZoZ8I7gzfS2poTt4G/6o40K9U8Qhb/kFsnLJjvUNS4MquDS72eQ==,iv:ji1MidsZtqFMxEBBNfM1shgI15Rd1cu7sQ9lK/9JGfM=,tag:2TT+9qcSCx4+pOXH2mXywQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMlV1a0djQUZOTnVPaVpQ
            YWRxVnZMSWNlM01YeVJNNGJibDBZVjFTTmtBCnZyZTBSYmc2WFU4RUxXS1JEZDhi
            VWFreThGZi9lT3ZqdlY1V1JRN2tVSXMKLS0tIFRUSVBDc1U5Z09FaU44MWlGMDV6
            SlJNOTlOYjE4OC9GY01uZ1lwUUFwYlkKrk0Gvb2OLO/VuiTZugD4sIduwjFaRMC2
            d/38cVDgAfkeWXhe8SMnxiL5u9ufD+DKiKff55pc2rOigvkRoye5iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-26T05:56:45Z"
    mac: ENC[AES256_GCM,data:UvNQxqj1C5Jh/iGmsEHF910Ct7dWcFzpPVUhYAQ0yy4xzoW+yT5ATHF7GquIgfWUuIg9UI9JIalRiaKxEGCov5jwqBYCsCUrfzB7/axAKrcATCA2tZ2TfE4FQyoueqHCX9OTgwEvdlsYL7Gsm9XiznvMlpQCm2fr1M1XYKIgt7M=,iv:c1zig0JWEgkynWnbHp0eCak4VSU/DrhM/kgTbt6Hq0s=,tag:EwDT483+W5XNdKNxBxId9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
