apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:M17jDwKtzY8/aCxofDxlrbbR2aBBXptQ+s++RYPWKnLTgcCzwrWIaC8=,iv:wElnUqaf4NNQjlElcXhijc88DevlybQLd5CLgTvnf70=,tag:aqkEZtI1miMe8PWTi+640A==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:0qoS+dBSOZ1Pris55Mnvwe45AZdELnsAapsl8/WI,iv:LaZ8wZFQfJgecfSfNAO6Cmrb0607Q+b+mizFwEuTUVM=,tag:4VN03f91W4ndLvttjHMrrA==,type:str]
    BW_HOST: ENC[AES256_GCM,data:KBRVOry+TTJ3jysnwXgk,iv:/7UANAtfrQ6Itx0ValYeK4LN3WiWbACqNUdd01+3jfc=,tag:bZRIjaF9HjD97JYK3/d6mg==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:PNV1gLMK7ea/x0LsaOvKEdxACGk=,iv:xAVP+hmXHVljHwS/zQAegO4qXC/38qDkIemvq3f73+w=,tag:58RGihxY5ByJpBHEstY1cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTnlkRmhiclJDOWdEdXVz
            dXJsUDdRUDh3eFBNNTk0akdtdURsQ2NVVkZFCmxycmxlcG5Rd29GK3FiSjlKWURp
            ZENOVUYwOVkvRDF6SXN2bnpic3hxV28KLS0tIHoxc01jSHdVL25jdE8xejN1cStG
            cldLRnVyRkxWMFZTWTRxRlkyck5pSkEKAEJcYquWHh/zpdVtt1chpfRheg3MFftj
            qdd2534iBNwoVG5rnYMAOeeztHMha0I3l/LIQtXEWpyrmDr75p/HFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T09:48:48Z"
    mac: ENC[AES256_GCM,data:tYpUUBV6SuMnY8Em8ocBavyedaAXstzE66WbGNFmSacmNE7fx1ryPrITyYGcZAXBJr4iSjJ+gKz2mLPix2Tqr4x4paZrsdfMzHjR7aYXXL4NySA6eekg+S9G0F5ZE3QBUfp+ANrmlKrOhHg12nOA5If+zOPnpa8pVNGZfOeh3mo=,iv:qjx/6VWdorY+rXjlmEZlQ0sw/CSJRbRjLRrLpWbFU7U=,tag:2m/VbkTpe2M6K9w4bTr86Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
