---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-opencloud-pv
spec:
  storageClassName: media-data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.internal
    path: /mnt/DataPool/apps/opencloud
  mountOptions:
    - nfsvers=4.1
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-opencloud
  namespace: data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-data
  resources:
    requests:
      storage: 1Mi