---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-opencloud-storage-users-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.internal
    path: /mnt/DataPool/apps/opencloud
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-opencloud-storage-users-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  volumeName: nfs-opencloud-storage-users-pv