---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  # Flux-Kustomizations
  - ./autobrr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./qui/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sonarr/ks.yaml
  - ./seerr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./navidrome/ks.yaml
  - ./slskd/ks.yaml
  - ./lidarr/ks.yaml
  - ./soularr/ks.yaml
  - ./explo/ks.yaml
  - ./feishin/ks.yaml