---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age15afcz4qr4nle0wjg8l3u32jn5jklu3yaek6yu7eepytczevs7d0qqym5gc"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age15afcz4qr4nle0wjg8l3u32jn5jklu3yaek6yu7eepytczevs7d0qqym5gc"
stores:
  yaml:
    indent: 2
