---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret minio-secret
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: /minio
