---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret explo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        LISTENBRAINZ_USER: "{{ .EXPLO_LISTENBRAINZ_USER }}"
        LISTENBRAINZ_USER_TOKEN: "{{ .EXPLO_LISTENBRAINZ_TOKEN }}"
        SYSTEM_USERNAME: "{{ .EXPLO_NAVIDROME_USERNAME }}"
        SYSTEM_PASSWORD: "{{ .EXPLO_NAVIDROME_PASSWORD }}"
        UI_USERNAME: "{{ .EXPLO_UI_USERNAME }}"
        UI_PASSWORD: "{{ .EXPLO_UI_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
