---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spoolman
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      spoolman:
        initContainers:
         config-permission-fix:
            image:
              repository: docker.io/library/busybox
              tag: latest
            command: [ "/bin/chown", "-R", "1000:1000", "/home/app/.local/share/spoolman/" ]
        containers:
          app:
            image:
              repository: ghcr.io/donkie/spoolman
              tag: 0.22.1
            env:
              TZ: Australia/Sydney
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 14m
                memory: 431M
              limits:
                memory: 431M

    service:
      app:
        controller: spoolman
        ports:
          http:
            port: &port 8000

    route:
      app:
        hostnames:
          - spoolman.narden.au
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        type: persistentVolumeClaim
        size: 512Mi
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /home/app/.local/share/spoolman/
