ansible_become_pass: ENC[AES256_GCM,data:r+2MpnbqTQt/XkMjHA==,iv:ulittSlGkX/FnJ1tZMCZ5zMiaDgoXBEFI9gI4O7gMq8=,tag:86Zq7hkJJFiWNwFRL6nEdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN09KbjZZL1FidnliSUpj
            U0xhNE1QREtwZHV4UndGc0pVcW1VaUhrR1JBCkQwUHMxK0tmajZ2NUgyak9iaHZl
            VmdtZkZDUkRENHpDemdPK1h6SmlTY0UKLS0tIHR5Z0E3a1lnMmlmMjNrbWFxM2E0
            YzJLMytqaENpMUJla1ovWlFjc2pOVjQKnRYJPXdV1wRwYkwCt//9ufW2puyeAP4e
            x/uAxuecKFbNDwRxIEAy5uevI8ukcZ5BSn/9X8LLSE2PeNgp+TA25A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:23:34Z"
    mac: ENC[AES256_GCM,data:OeRjZVtDTtdnhMkZEfT9I5Fw66gTxddfWjcX7jj57jv7yQHjIE/FLDGg13ANY0t55lCQAVn9pOdg8RtqWNWGnMFYka7iY+7Iu05UilEIzSbH46DR3uaSKHa4L2GwdU3DKpXtU5RIy0/1E1seZV0q1OkwJwXmfDL5tuI7EwzNHjY=,iv:mxiWORldz64Y2H9NwBPsExY0xYyx5kH/aCIzy0/Yudk=,tag:ui+XqyO5aMkkVZ6gK2qatw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
