ansible_become_pass: ENC[AES256_GCM,data:lUpXxsK4ZA7UdhKVeg==,iv:xC6eV8IhatFbbjy/qcOArenrcC3qB4Q5ENRxpmz8KrM=,tag:6Dx3ZKbRGCydP85FBAGibA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaVByNkZYdVQ3ZktvMWxo
            S1ZacWp3cm9uRm5OQlhtYjl5SmZVb1Z6RkhnCmV6YmtKSStUaENQR3ZWTjFJOTJj
            YitTZHpPMU1rVkFnZVdCWXVyQTJvaHcKLS0tIHJjZmFpbDNkVUF6cjJhRjBOK3Yv
            K1U1eWdMSFNkeE43MGxKc00zMEYvQ1kKzBsDnQpWL/xEDQfQ2Vl5EpmQO8o22dlT
            1hGnX1PKVVWLdQXUXtKRJqsXFWCNn+tPDZL9j70W+LDjwB1CzEBQiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:21:08Z"
    mac: ENC[AES256_GCM,data:Nt3MsKakVyG6f/sC3RXdo6CMvtfni/7vdkiR0L7sPchKU0I4hEm3JNcGQG7g6veR7SAseqG/DQMsa2LyFyeGtf3bdksay5OmAGXjlAWsuql7VwMzTgqWdHvUzTHQCql/YIVXkfVLvchIwRMkdRTTWzAAIlrvyvhCwy7HjbxEDkQ=,iv:550rgsvBXCQAw/5DMzP6bunR6skK+Klsabz7NcCF3vk=,tag:iPwa8V/PaQdHU/LA+RgkbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
