ansible_become_pass: ENC[AES256_GCM,data:hhzbwY/fBKTWwNv+kg==,iv:aq5vGgmA6OtQZNy0W3k4y3diHPNQwjDbTWaG+RgmZSU=,tag:FUiIKYa8j+YP8V7cpV0XhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZEQzdVdPQ3Z6MEFidGx3
            S3dKeWJqaC9UNGh1VmhqT3FrbWVrRmJTZVFnCmtqZjkvemJVMWdwbFc1bkJNNmJr
            MjlHZlhPK3U3YStGaDR0M3RobG9sVjAKLS0tIDdRNjFsOThDcUJFSVJNZ1d6Vk5I
            Y3VnbXlveEJGSXpXc09tQmpuNWZxbmMK+lbEKPM8KHFiry7qhpWmYa/a1Ei+eoiQ
            mAF6IYGEVnW0Lw34ZwV/ICAd6XyBFLepQKvWl8GSQaB+7l9b5bbKZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:23:34Z"
    mac: ENC[AES256_GCM,data:LTjE3M02FANFImgvvJ1JqCis3EjnLNM9KSHl853Ub8bG5makwIiWEhGI/peRpl4SWuugTqffslSiaLypxmcjLObCQW9Zv3TnWDC8XlETG5c8VF7pVnsqBmT6EAcIMZRLCtUSCpe0ZMZCGDXazPRbykGSX5mqxoLzMue4dlbrl+Q=,iv:aP+wQwx6uSB/Z6V9m4z+DIYwYhuVEtk2PJA5wH8Qa7c=,tag:FJZ4Hd1gWgzZhOYlTZP5lg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
