ansible_become_pass: ENC[AES256_GCM,data:xzxKnLNmGb+Q4tJnWw==,iv:ZJ4tqjLmyOKVLsRoFUaGvfT0RHw7hR03ih57CC4V/QY=,tag:uTckzEuFh6UZ/WaaTKJa6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRWJxcm45c0luQ2g1cVE3
            ZjBlQUN2bDNROSszZUlpSDdwVnpCS3VpWVdVCjZKTHJBYXBseDNod3pFVGlGbTF2
            WlE3enNPZG9XSDBiUzE1cWQ5WS9VaU0KLS0tIERNMjE0UFdBUHdEME54OHZRQ1dI
            OUhjb2JlVThJcXkrQ3FWVW9acmFFSUEKwgIu+Kvbn6/HyXQDp9nLFUEMQyUx9TI1
            6TyXehiOwJSN1zIf5PHNNGvMHx4UjfbXQHsXEDyJtbMZ2+vXaueD+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T12:05:34Z"
    mac: ENC[AES256_GCM,data:5C8ooQ9/BRYzRrBv6VDlWM9WCVZUwc0QO/IBynxwarsX+D9NmFkokm/CoWBxtqvTkgr1VqPRLT96ObuUiudGlhyZXT/sz6QC45Xq2o7Jght+rE0LlbrIesYuItavIqFBX9O9cwhK2rDW0f06nWroasC1Cfo2vJgVOMbtiZM2jPg=,iv:L9ewHDknIxZ2R0KX7uuRhIpJ+xFBxAxo691DpBtlSqA=,tag:SAnDhShDhbFrf1gYAz9HKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
