ansible_become_pass: ENC[AES256_GCM,data:apNgFK6AhBwyfIk8eg==,iv:dN+yUnlUjlY1JZo7YVWR5XxiuhN4rvclllL6reTzodA=,tag:5pZDCyS9aEHGzJrp18sSgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL1B4VHpwTFJuckhIMUEv
            ZjE2ak80NmZIekJodzk3YnhKQ0NpVUt3T1U0CmpMckNwZG0yd2VnMEpqc3dpM3pX
            K1k0SHd6TGVqdGVOTzZsajMrNzc2L3MKLS0tIFRVK2xDakdUNktxYjYvYjU5MTN2
            S3JJY1pyamxTa2xpVVBDYWVSSWY3c3MKdGxVvSDVs+J5SyPLCvM5qu6gY809qv7E
            zPRoK/usCk9cr/iwGcEpFD0bcEEiDY8kjCzcqaJYppvb1AjOKiVFPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T12:05:34Z"
    mac: ENC[AES256_GCM,data:gPZONV8IhIA7e+L0xPx+KkBp8w1PD2OgXms5H7VOLei25fHzNHqbZ9FU4JD3gZkMcvERI86pwEncLCmYCAeqC8gk/IuoMSzZY1K/UWfDQo6IQej6/+43x4ZQBIhv+x2FE26w7P98a0Y8ZpYt8sBrEPQeATcFWxQM/tu44NO2+h4=,iv:SojmTzUlmyKCYYrXWair/HXBOznt/Hww0PpN6/o2wbM=,tag:kXKXNlYmaZV8yUJjg4lwyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
