ansible_become_pass: ENC[AES256_GCM,data:02lFtcBqcyZZ+Rr43A==,iv:A9KZ3beTtpywMYkYKbzLhblbYMzztuv4N2aQNepysuY=,tag:gKyX5Z7P6hYBXjDvY6CqbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMGUyWnVPVUgxVzJEQTJ6
            dUhGN3JCQXhFYi82WXJkb0hqL2J5akZVN3hzCmx0Vkt5dis5QXpCc01jcWQyNS96
            anVvTzlsSnoxMzFMY3NpS3Q4VzNSS3MKLS0tIE5NWDNmTE8rNUdkWFJCWkZ0TzIz
            YVY0ZEFMQmJkUTVDcTM2eEphdGhtcE0KLUReeRmLMIvu8r0xHzN6BDFImyH8flMT
            hVIeWfOmufqf+b65JuaxTDyLH37EN/9WJM0rmxn8hgP36qs+VwKqYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T12:05:34Z"
    mac: ENC[AES256_GCM,data:VmnyrUkasok4ikm5KZMpIzKBvmmb+IOFmmD1V1X7z0JbwdqJT3RZ7OGgoAJAdwo4WAU4LqrmAbUFsmCYB5cJ+dKQ1CQDBJVa+VsWJwlaHtcrGFsBhxud6cCzwWiTzd1Q7UXDG5nN7kS+bAM3WgV5QG2wS0wA51glO3OhlB0wHpc=,iv:HCXAorQGViwbfhhUbmEW6eheiet32RSSbTArPeqBzQY=,tag:StTZO4ze9KEx7yzQ+6xnpg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
