ansible_become_pass: ENC[AES256_GCM,data:t+JB1i8+eb3D1Ugm3Q==,iv:HKagrWwPGfoaUIXzxs5xO5vMp5eNO8E7aLJvH+hvt4c=,tag:tAm9znELait98xaQhXXlTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvb0VQRnVPV0h2OGFHY3BV
            cUJhallmSzBwVkxiRDd2K2p3cGd6N29FZEZnClRJMkE0RmllTFI2ODd0N005WXBn
            ZDNLWnA5WmhRNGttWit6S1lVamtWRDgKLS0tIFV2UlB2ZTJhWUZjVnJMS3pab2s0
            WmVJbTFDN2tHbGtTMUlUcCtQQ2N4c3cKgrDUH1utVEcOL7RoK2DwWDdYqQal1rtf
            4tV6KX04ogeQWIkTfZHvQQ7EueCSRO1qFeAkAjMIxfSpET03/y64yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:25:53Z"
    mac: ENC[AES256_GCM,data:/16xbDCcHRdVBfAN+lzrNc30ke66ZmlDkYBRjvBXlaTY/ZsXkTtwEo//MlLixU8xBNuCSgn4yzNijlURRrUGm1n4wPaUoCvyQAKrTrQx64KmBACFSTOYL/NqSD/Q6kfYshjwWuS/ZIdKSQ6UvAcOcH7MQfAj7RQ70LKuyFAcNjE=,iv:H/blevYUcRhAgNG2uQpc43Nyutl93RhQ0e1mMwcDUN4=,tag:bYzwcPD82g7amwLIKzcdFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
