ansible_become_pass: ENC[AES256_GCM,data:WhT8v6adtxnUaoxOUA==,iv:49Dg1u7p51Okdx406+vMmnSYYfD1Qf5zrWp3hqd3TM4=,tag:LXabHxaVhzU0tVKKohrqFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YjdyVkVCZjFPVFVHZ1kx
            NkptZGplVVZDZnFNQjEvTXJXZkJhaGZNelY4Ck9ubERlaGhGWEtTbnZPb0JxYWVl
            MDZHRWJmU3czVXh5eHAyNTVvNXBFclEKLS0tIElHNVJ4UGpnMVcrbjdyRlUvS2dw
            Z0MrS1Q2dlgxdDRBb3lML1hUNTJiYkEKlDkfl56EmAZpjJ5XJtJsKIhCMlqLEVz9
            AbywMqCfhIacVcF2jFIUt6YBvQaex1iFwWxClo5thDZKP3hVB3/98g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T12:05:34Z"
    mac: ENC[AES256_GCM,data:oByDu9X6LBg3OloyYMqw3jH+/SA3YMTjRaOl8UkOK/+n83W+/cYBCalCcD29txy8oyKCevFBmPmpB1NzpX23wLEaZWKaVGsQqlXb5OjYkr4p+Hixc0YuIXePrH5FfYIJ0+vBrG0rl8ET8ZydmoIz82flNA8EExsoz8WsYMdqK4I=,iv:gGgRoVkCZIER3z+7qSJO/O/sCNx21WOyREv0TFv7/FI=,tag:sd37AIKPUCEUHxMf+FgUNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
