apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:aqFO4iq7ngx34mWKBJ3QbQI+X7Ml9IZ0y9LAl7jsguptDcXn,iv:/FUJ8SLWRkAB9PNz1DV3G6nBhcA3pKuL9rsh7/dhScc=,tag:exwe2EkdmWmZD+IAeweEfg==,type:str]
    credentials.json: ENC[AES256_GCM,data:WKLvSZ5aCdV/pVyMxM6/GtvWwwbjTVKnss2G0yBFuK7FInlX18tLIUJS9KNWsSGZsDuiF//SFhRkX65gP7wRj8b9bqbrnl5qx2rbjFEC8NxGSufwjpuNGcYTDxZQQks3gsVlD6KKaBt7WAm/G88App1JX9bWPg1W04NFdhDhbzH7E3R3+zIiWD6yaCsadmSVInB0JWhXIrrOcjJNUf6ODTdLCsRTnpVfLs7nS2/eNA==,iv:Ndu4964YQRzTNyTRmleaqOhviB7tauHIrooZddG+1TI=,tag:eKo3TNykEtX1xhRqDLNrBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL2RNRm5PNWEzSTNjY3dF
            a3JCb0NXdEFsaFZUUEJTdWp3Uk9ZMTRzZkcwCjJqSjJyYmRrampnVmcwUld3OXF6
            bFhTalFINVVpZmxQMkhJWll3cTFrRVkKLS0tIDJCM0I3YzRSUXYvU2pqWGR6U2h2
            ZTNCVG1lSWVpNnFiVGM1b3llV0hSRG8K6DwuXOx1MGoJFNxA5Iy94Hv1bItHhF22
            Nf0+cQIaCC1ctcPN8vx+M+H6jWkHkrXKJZk8fpH2pOsnzsxhCePB3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-19T06:19:05Z"
    mac: ENC[AES256_GCM,data:3on37CIqd1z3WfZj8bKXbAb/ghDbUj3fzC7mnmMHLZXIvC6FnQ0qur8spphOwDyUk30OMKfUtKo876sUk99xI0WnWagaboQUXhiLTzhYNAgkrebtYUDA3oBlDJ5cimLOXOq6wvqIrDgxbTvFHBkKB/jdGTm2oOf81s74egPsql8=,iv:torGDAJ4JoJfFcqdKJq3DGARP8tgUdAQ1yFudI7qh94=,tag:f+CuBQg99cPGwuBTKkDlXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
