apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:4qrVE3BMcXlsc2LXpuePL7vQj4qkUjMJan79ksJ5Zv+ysevb,iv:epiI3gCpA6ZeNU3UB8NrCknevooVILGrsHbDp9W1Hjw=,tag:+wFtFseZ/MQsnnlkvwHkKg==,type:str]
    credentials.json: ENC[AES256_GCM,data:/OqAjG3E/OWr51bkJGyQTfj6JfgAzDrx8AutxTRHyMIvRwlSMrf5QJ0htv3fC+ea/XPWDLertOVSsGGBsHlscDq4bwtdanp3NCqNSEwEiC4/XOp4pZ6Wc3daUA1nyxJ0+HXwbHKmS1N7YJQu8K1ck2TgcB0/ydoYMHuEQer4VqwJzPu5CsuzjGMRqiN3I5pnJXPY6vV9cnQBCEQaUmUFk3i0P50xXQBYVQluzhxMsg==,iv:iUSDfzmrsvjic0k/u7gx5bSO3EGbclxchchV9X3fp9g=,tag:8kV5RqUfoSknpFA3vuYwkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVWJweUhxWk82eDgxSlR5
            Z2hHK1lyVlFwTzNHdlFiaHo1bVZzcG1YOUZRCjNnZGF0Q2V0MTFpWDE3MVpObUJJ
            U3ljcWF2SGJSUzBScFNpU3l5UGJBVGMKLS0tIGZGK1N4RUdaN2tjOFFPVWkwVGNU
            MFNTVVE2cUthQTR3MnRTUkUxbGRjVm8KzuPpoBXgfwbrs/+RLC1j+oVjYIzuOcLk
            fbPF61aKVCdCwjW0+7PsSe1btZ+w4lB5E7XkuJrsUYIhV0QK8DLfiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T12:18:42Z"
    mac: ENC[AES256_GCM,data:hb7P/7s9ymqOArTnM9TPyHqMp3iIN8HZdCs2ZsjX+o68JFOrFhjDEBSSksj2eJcNK1XytPHWUf8rKu4jaoVKteKnb7myDfW/wBYP0cdncKp/6bTvy03KcHwENPFsbv8bq1SraBz5oyS96A7IvcruEcYd1pvJRfzygWgsNQzx/uI=,iv:PLPhxWMdRlON8inzzLCZ7o9PSjdEzRtuy7hDtSzLgP4=,tag:QUxtPuTdEBMGQO6X4/FmVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
