apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5dGT21M0CL0IepP4KfqId5CFVW4Hh01ro1iX4/SUQAt8wHy6,iv:9cbcW3nQXfRaAuLi8swufyJvPlm4WBT9HWb1B8C2BHk=,tag:JFlaOOHnoX8/9ZOpFh2Vww==,type:str]
    credentials.json: ENC[AES256_GCM,data:fs4dYSjf502QMxlQMe2MMxMk90CknZJZXIDS0NCEi2EBV8XZOvPh7jc1LEJWfu4ECR1dRmoFSt1VQFlT0V4Ey/ut1KUA62fV2PP2hoFN82/a5N7+gtiF51xQ6FW9MpZnxGhK64oezvhL1wHxeXVQiwGip0hDXHxl5DVc82nbCfmh+8DXB4uUqpFaaRp4b++ek/47n81ug/MsIJXpAhdxddfT05RQd84Acmtb+usCMw==,iv:f0LjblpiyB85C2JQmlCiAG5DSsJEwoygnE2FJt9wM7w=,tag:17sm4tHoztsXHX9x2tcSnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeDNKVVRBZlJTbnBjL2pQ
            am81emN2UWFkNjBGVTNEUCtmZHdhMlI1N3pNCnZzUmJaMGE3TUg1ZGJFV291eTV5
            TDVSdmEyd2N5aFhnWnhXMUF1c2tQejgKLS0tICs5bHphUkJUSGlUZG5iRDI4NVJU
            RjdHVFhzeXNYSjBMcmRGQTVrZzEyQVUKKEQrJ//FK2iZpiJaB38ccJjyEDnvrvBf
            kVeFhdrRYSdX+u94OYGfQk0Dgc9fz7N/C1vC4K6WzRozJ6L10rUCzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T12:17:34Z"
    mac: ENC[AES256_GCM,data:Gxd5nzOJzoMG3F03iay2aWcxI+YSqIAFKzsfKLUsCAGeJruG9ESS6vXM2ynDqjudXgoI8mC5p3vy50dptC6yla7Q7lS4vbfvRpN6vAeOo9pXj9oetQX58umOSZ32dtlUbdcQUCXJ0zOSWyXZxpOCyuV2mOzU4jUeG5mcIPIZn70=,iv:val6mSRuQLt8QT5hCgxiIq8G7ZYrss7OwvGists++j0=,tag:LBy9RWw8FciEXMqtX3VOdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
