---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ups-alerts
  namespace: observability
spec:
  groups:
  - name: ups.rules
    rules:
    - alert: UPSOnBattery
      expr: network_ups_tools_ups_status{flag="OB"} == 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "UPS on battery"
        description: "The UPS is running on battery."

    - alert: UPSLowBattery
      expr: network_ups_tools_ups_status{flag="LB"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "UPS low battery"
        description: "The UPS battery is low."

    - alert: UPSBatteryDischarging
      expr: network_ups_tools_ups_status{flag="DISCHRG"} == 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "UPS discharging"
        description: "The UPS battery is discharging."

    - alert: UPSBatteryRuntimeLow
      expr: network_ups_tools_battery_runtime < 300
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "UPS runtime low"
        description: "UPS battery runtime is less than 5 minutes."

    - alert: UPSHighLoad
      expr: network_ups_tools_ups_load > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "UPS load high"
        description: "UPS load is above 80%."
