---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ups-rules
  namespace: observability
spec:
  groups:
  - name: ups.rules
    rules:
    - alert: UPSOnBattery
      expr: network_ups_tools_ups_status{flag="OB"} == 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "UPS on battery"
        description: "The UPS is running on battery."

    - alert: UPSLowBattery
      expr: network_ups_tools_ups_status{flag="LB"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "UPS low battery"
        description: "The UPS battery is low."

    - alert: UPSBatteryDischarging
      expr: network_ups_tools_ups_status{flag="DISCHRG"} == 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "UPS discharging"
        description: "The UPS battery is discharging."

    - alert: UPSBatteryRuntimeLow
      expr: network_ups_tools_battery_runtime < 300
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "UPS runtime low"
        description: "UPS battery runtime is less than 5 minutes."

    - alert: UPSHighLoad
      expr: network_ups_tools_ups_load > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "UPS load high"
        description: "UPS load is above 80%."

  - name: ups.aliases
    rules:
    # Battery charge (percent)
    - record: ups_battery_charge_percent
      expr: network_ups_tools_battery_charge

    # Estimated runtime (seconds → minutes)
    - record: ups_estimated_minutes_remaining
      expr: network_ups_tools_battery_runtime / 60

    # Estimated runtime (seconds)
    - record: ups_estimated_runtime_seconds
      expr: network_ups_tools_battery_runtime

    # Battery voltage
    - record: ups_battery_voltage
      expr: network_ups_tools_battery_voltage

    # Input voltage
    - record: ups_input_voltage
      expr: network_ups_tools_input_voltage

    # Output voltage
    - record: ups_output_voltage
      expr: network_ups_tools_output_voltage

    # Output load (percent)
    - record: ups_output_percent_load
      expr: network_ups_tools_ups_load

    # UPS status aliases
    - record: ups_status_online
      expr: network_ups_tools_ups_status{flag="OL"}
    - record: ups_status_onbattery
      expr: network_ups_tools_ups_status{flag="OB"}
    - record: ups_status_lowbattery
      expr: network_ups_tools_ups_status{flag="LB"}
    - record: ups_status_charging
      expr: network_ups_tools_ups_status{flag="CHRG"}
