apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:kCVPWpFndKlvhh7Oy5YDfnhhMya6gSq3,iv:gu8wtgUV3ryZoCKtTTQm6QUmz7rT446FDbx3477U+2I=,tag:sY/0YBbfoWZWuSVCwT1vhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MXIxdjc0c0RGaEdBeWFR
            d1JnY0xZamhEdFllN0IyODltOUVvYU5NOENrCjlwR2lkVWZLc1FmbGF3UWZMblJO
            Q1IzR0w4UmhEeE5xM0VOVDNybTByTHMKLS0tIDAzOTRGUTFzS3g5c28yVWlWTE11
            Z1JuUnNrWWMrKzl0UjI1ZkRqRGRuREEK0Sf3A5aNAB1MYTqhRx4jFb0RZRHwD6i1
            1hZtvjOU/r1EthnLRdHtt9IgwYMhzkTVYzWGbljQ7iqdvdtUYPpgfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T12:06:05Z"
    mac: ENC[AES256_GCM,data:9PxoJWrlPbdUxeT/ScHavInkTYMYs86ejiffv3g3/1+q0uVlPN1NsGgx3kDK7YuW9aLMI2odHrQ6FoRfG7hS4RwQTdeBvSB+quufmPBe2WHeClXOb/jJHHKq2Q0icZrX01FFnka2LftwbMLtV8S+11i9X/9sZ7XlZvG6fI8qNgg=,iv:jBxVgR6wg/pxMjavwNjJoDW+ueVcbB0IKtcICrSNow0=,tag:ElmQBTiKggNDMR3gNxlw0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
