apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:J8j58H3BnVceCTG1vaupFYPjaAhpPS++,iv:4Ns3xRyOEPGN1ErpiItp87I0BeIxELK3opm8y62ZVZI=,tag:EqVVxREIgUxyBhxYxaYD2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVY3U1l6UXBxenBVTHJq
            SUwwU1EweHpmWURGaStqZHYrTm5PTUFOT0RrCnpZRFdHdytWSE1WbVg5ZEpTazUy
            ZkxwOGdjdXJVWHY4ZEdNRElHQWRLZ0EKLS0tIHBzSWxTRFEyWUYrSW9teDNxNHlH
            ZVZvalV3NmtjS3hpQXZ2SFBNZlZlSDAKmsupLIyNc13zSvOU1IVVZcMw12u1J+IT
            qmqXoamuXqSl7g/IeazJnX5Iq79GZ3N1VxM2KdDl1eom2gCGPlnFTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:26:24Z"
    mac: ENC[AES256_GCM,data:ucojA5erG8BU6flFYgrCkwKYypLhPYuvA8rSsLviOv5KDZhoR5WuEfzUp/179E2YSEWlDZeLlkaCHiXFmI9Pgvbf3354na//layW9MlvPBr/mFhqzfjX1loIjfkZkFl/wjxmiHBeGRV6d6Gr74WPFB/essI398sw5JtjLVWC+iQ=,iv:S8thSmvnapfkyUAQDz38kO3Vw1YeKqGieHQwYaJIkOs=,tag:k1cLbtFjEN/0IWpkMg62sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
