---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app obico
spec:
  interval: 15m
  chart:
    spec:
      chart: obico
      version: 0.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: gabe565
  driftDetection:
    mode: enabled
  values:
    server:
        image:
            repository: ghcr.io/gabe565/obico/web
            tag: sha-50b9a9cf770c3dd444bf7488cb9b1ba5c96dc8fd
        env:
            ACCOUNT_ALLOW_SIGN_UP: "False"
            OCTOPRINT_TUNNEL_PORT_RANGE: "15853-15858"
            #envFrom:
            #  - secretRef:
            #      name: obico-secret
        ports:
            - "15853:3334"
            - "15854:3334"
            - "15855:3334"
            - "15856:3334"
            - "15857:3334"
            - "15858:3334"
        persistence:
        data:
          enabled: true
          existingClaim: obico-data
        media:
          enabled: true
          existingClaim: obico-media
        
        service:
           app:
            ports:
              http:
                port: &port 443
        
        route:
          app:
            hostnames:
                - obico.narden.au
            parentRefs:
                - name: external
                  namespace: kube-system
                  sectionName: https
            rules:
                - backendRefs:
                - identifier: app
                  port: *port
        resources:
              requests:
                cpu: 50m
                memory: 4000Mi
              limits:
                memory: 4000Mi
        
    ml-api:
        image:
            repository: ghcr.io/gabe565/obico/ml-api
            tag: sha-50b9a9cf770c3dd444bf7488cb9b1ba5c96dc8fd
        env:
         DEBUG: "False"
        

    

    

    
