---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret linkding-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        LD_DB_DATABASE: &dbName linkding
        LD_DB_HOST: &dbHost postgres-rw.database.svc.cluster.local
        LD_DB_USER: &dbUser "{{ .LD_POSTGRES_USER }}"
        LD_DB_PASSWORD: &dbPass "{{ .LD_POSTGRES_PASS }}"
        LD_DB_ENGINE: postgres
        LD_DB_PORT: "9090"
        LD_SUPERUSER_NAME: "{{ .LD_SUPERUSER_NAME }}"
        LD_SUPERUSER_PASSWORD: "{{ .LD_SUPERUSER_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /linkding
    - extract:
        key: /cloudnative-pg
