---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: konflate
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.32
  url: oci://ghcr.io/home-operations/charts/konflate
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  chartRef:
    kind: OCIRepository
    name: konflate
  interval: 1h
  values:
    config:
      repo: github://philgood/home-ops
    secret:
      existingSecret: konflate-secret
    persistence:
      enabled: true
      size: 5Gi
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/endpoint: |-
          conditions: ["[STATUS] == 200"]
      hostnames:
        - "konflate.${SECRET_DOMAIN}"
      parentRefs:
        - name: envoy-external
          namespace: network
    monitoring:
      serviceMonitor:
        enabled: true
        interval: 1m
        scrapeTimeout: 10s
