---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret teslagdo-secret
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.yml: |
          global:
            tracker_mqtt_settings:
              connection:
                host: mqtt.narden.au
                port: 1883
                client_id: tesla-geogdo
                user: "{{ .MQTT_USERNAME }}"
                pass: "{{ .MQTT_PASSWORD }}"
                use_tls: false
                skip_tls_verify: false
            cooldown: 5

          garage_doors:
            - geofence:
                type: circular
                settings:
                  center:
                    lat: -35.429527
                    lng: 149.234421
                  close_distance: 0.01
                  open_distance: 0.04
              opener:
                type: homeassistant
                settings:
                  connection:
                    host: https://hass.narden.au
                    api_key: "{{ .HASS_LONG_API }}"
                    use_tls: true
                    skip_tls_verify: false
                  entity_id: cover.garage_door_garage_door_cover
                  enable_status_checks: true
              trackers:
                - id: 1
                  lat_topic: teslamate/cars/1/latitude
                  lng_topic: teslamate/cars/1/longitude
  dataFrom:
    - extract:
        key: /mqtt
    - extract:
        key: /home-assistant