---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
    startupProbe:
      httpGet:
        path: /api/health
        port: 3000
      failureThreshold: 60
      periodSeconds: 2
    deploymentStrategy:
      type: Recreate
    admin:
      existingSecret: grafana-admin-secret
    env:
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_EXPLORE_ENABLED: true
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: pr0ps-trackmap-panel,panodata-map-panel
      GF_SERVER_ROOT_URL: "https://grafana.narden.au"
      TESLAMATE_DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: grafana-admin-secret
            key: TESLAMATE_DB_PASSWORD
    envFromSecrets:
      - name: grafana-admin-secret
    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      auth:
        oauth_auto_login: false
        disable_login_form: false
      auth.basic:
        enabled: true
      auth.anonymous:
        enabled: false
        org_id: 1
        org_name: Main Org.
        org_role: Viewer
      news:
        news_feed_enabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - { name: Alertmanager, orgId: 1 }
          - { name: Loki, orgId: 1 }
          - { name: Prometheus, orgId: 1 }
        datasources:
          - name: Prometheus
            type: prometheus
            uid: prometheus
            access: proxy
            url: http://prometheus-operated.observability.svc.cluster.local:9090
            jsonData:
              timeInterval: 1m
            isDefault: true
          - name: Loki
            type: loki
            uid: loki
            access: proxy
            url: http://victoria-logs-server.observability.svc.cluster.local:9428
            jsonData:
              maxLines: 250
          - name: Alertmanager
            type: alertmanager
            uid: alertmanager
            access: proxy
            url: http://alertmanager-operated.observability.svc.cluster.local:9093
            jsonData:
              implementation: prometheus
    sidecar:
      datasources:
        enabled: true
        searchNamespace: ALL
        labelValue: ""
        resource: both
    plugins:
      - gapit-htmlgraphics-panel
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - pr0ps-trackmap-panel
      - vonage-status-panel
    service:
      type: ClusterIP
      port: &servicePort 80
      targetPort: 3000
    serviceMonitor:
      enabled: true
    route:
      main:
        enabled: true
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - grafana.narden.au
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      enabled: false
    testFramework:
      enabled: false
