---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: sonarr-oidc
  namespace: media
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sonarr
  oidc:
    provider:
      issuer: https://id.${SECRET_DOMAIN}
    clientID: 78b3e218-f01b-4024-a00c-c065503592f0
    clientSecret:
      name: sonarr
    redirectURL: https://sonarr.${SECRET_DOMAIN}/oauth2/callback
    scopes: ["openid", "profile", "email"]
