---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tesla-proxy
spec:
  secretName: tesla-proxy-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: teswall.narden.au
  dnsNames:
    - teswall.narden.au
  privateKey:
    rotationPolicy: Always