---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tesla-proxy
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: tesla-proxy-secret
    creationPolicy: Owner
    template:
      data:
        PUBLIC_KEY_PEM: "{{ .PUBLIC_KEY_PEM }}"
        PRIVATE_KEY_PEM: "{{ .PRIVATE_KEY_PEM }}"
  dataFrom:
    - extract:
        key: /tesla-proxy