---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret tesla-proxy-secret
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
		CLIENT_ID: "{{ .CLIENT_ID }}"
        CLIENT_SECRET: "{{ .CLIENT_SECRET }}"

        PUBLIC_KEY_PEM: |
          {{ .PUBLIC_KEY_PEM }}

        PRIVATE_KEY_PEM: |
          {{ .PRIVATE_KEY_PEM }}
  dataFrom:
    - extract:
        key: /tesla-proxy