---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tesla-proxy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tesla-proxy:
        containers:
          app:
            image:
              repository: ghcr.io/adampetrovic/tesla-http-proxy
              tag: 1.0.10@sha256:2c2e722cd213623dac4e115448cc77aba9a7bed71f5022316aec38ad1245b6d7
              pullPolicy: Always
            env:
              SERVER_MODE: 3
              TZ: Australia/Sydney
            envFrom:
              - secretRef:
                  name: tesla-proxy-secret
            probes: &probes
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          setup:
            enabled: false
            image:
              repository: ghcr.io/adampetrovic/tesla-http-proxy
              tag: 1.0.10@sha256:2c2e722cd213623dac4e115448cc77aba9a7bed71f5022316aec38ad1245b6d7
              pullPolicy: Always
            env:
              DOMAIN: teswall.narden.au
              SERVER_MODE: 2
              REGION: North America, Asia-Pacific
            envFrom:
              - secretRef:
                  name: tesla-proxy-secret
            probes: *probes
          keyserver:
            image:
              repository: ghcr.io/adampetrovic/tesla-http-proxy
              tag: 1.0.10@sha256:2c2e722cd213623dac4e115448cc77aba9a7bed71f5022316aec38ad1245b6d7
              pullPolicy: Always
            env:
              SERVER_MODE: 1
            probes: *probes

    service:
      app:
        ports:
          http:
           port: &app-port 8099
      setup:
        ports:
          http:
              port: &setup-port 8097
      keyserver:
        ports:
          http:
            port: &keyserver-port 8098     
    route:
      setup:
        hostnames:
          - teswall.narden.au
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *setup-port
      keyserver:
        hostnames:
          - teswall.narden.au
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
         #- backendRefs:
         #     - identifier: tesla-proxy-keyserver
         #       port: *keyserver-port
         - matches:
             - path: 
                 type: Prefix
                 value: /.well-known/appspecific/com.tesla.3p.public-key.pem       
        
    persistence:
      #config:
      #  existingClaim: tesla-proxy-config
      #  advancedMounts:
      #    tesla-proxy:
      #      app:
      #        - path: /config
      tesla-public-key:
        type: secret
        name: tesla-proxy-secret
        defaultMode: 420  # 644 (octal) in decimal
        advancedMounts:
          tesla-proxy:
            keyserver:
              - path: /config/tesla/com.tesla.3p.public-key.pem
                subPath: PUBLIC_KEY_PEM
      #tesla-private-key:
      ##  type: secret
      #  name: tesla-proxy-secret
      #  defaultMode: 420  # 644 (octal) in decimal
      #  advancedMounts:
      #    tesla-proxy:
      #      app:
      #        - path: /config/tesla/com.tesla.3p.private-key.pem
      #         subPath: PRIVATE_KEY_PEM
