---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - "172.20.20.129"
        - nas.internal
        #- ups.internal
        #- kvm.internal
        #- pikvm.internal
        #- zigbee-controller.internal
