---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-issuer
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflare-issuer-secret
    template:
      data:
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
