apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:lVPncP72Es96YGeweZ8LrVkYtdhyU8ytmHPbOp+as94+CQL9921TTw==,iv:ozyb8aUx/TtLhRsdRBXC6mEGuKpxZ34RBC0+0zjn6gA=,tag:I8l6cq0/IUJYU10CEUw+4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVVFqQzhWanJvTmJIWnJS
            U0h0TGRtRVNwOU1yVE1XV21NZC9nYXNjVmlNClhEb0NzTmJ0ejhTSTlvdlpKUmRI
            S1VlK1pWUW5kakoweTlUZjF0SVNseTAKLS0tIFFIblFmQjZJa0NnalpuYis0bjRa
            S204T3FUVDk1WU1xdjZZYjZzcldBMTgKnWYaNcxPDSHR3G0n9bz4vQ2n1k7iJRZH
            11KR4ntKy3kvRXlZUCmUPRjqJypxPWjibzKHhrs2wwLtDxS1ZRN43A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T23:37:45Z"
    mac: ENC[AES256_GCM,data:9RWPrG3PGqN7SA/zXD8HpFqtta27kur3LMwVWoNk5nkglDP05nqVBN9boRQBfDJWYo7ad8vj/WegfeRpywGXfHwGYJ5wRjQQBx+Km5Hd179k0/eFlxKr9lRRBwqYpkvYv41LDKyIR1+fEuoEvgJ2TV2CaoU9xGh93M1146tuQkA=,iv:DaPE3hOWbpO/ZpA1OaBSvH13ZeIBvintz8Kr1scuFFA=,tag:lTxQET/HZZ8TnrqUkbczsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
