apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ETaNrBSSN01Xu7BrTRcz+NqAwuHVnCsB3d0SIcoLNRtYavSMH7rhIA==,iv:KzvCwdsr33R03wKErY53C+FbB47qIzMRI0wVh/vbAME=,tag:/5dDwd0W4PR3hmPxhMJiOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaHYrMzdZQmVFRVJ4cGRz
            QU5wbHBvTlpLSldxTE5tc1RNK0s3RjMxTkJjCkJ0RG9IOGRxY1d5T3lvRDFwMGN3
            T0lwUG1aN3VsS0FvWSs3VS9wZE1qNlEKLS0tIDdnd0dFdkYyNGtONzBBK2czNVhZ
            dENvNFRienJvWktzcFlad2dwU3JyRncKWNf9c3GDo7b8N7hfRMGeQHarmx+GpJ/6
            rKVW7l+VSibFpLxuVg8snu44RLG8VLwDRT9fIwy07bfZwBX2upKMVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T23:26:05Z"
    mac: ENC[AES256_GCM,data:DiMz3CXWIOKMU/NZrgt4rovCNrK0xeGoIT2jS64tQ9qVt/on59kAJggcirc5cK0pUSQ8tKgxnsPb6nR5G5vJaNeCfiX4b0jiKyce6XxPL2MOOWXCNx4Pw/htLTGR3YubEWcvrtEnmJ04APhS4GihWHAVQ7zklx6AVKDxGD0F9y0=,iv:SuyH/Zt1HD3eaErpXVJQA60LUGpk9X3HqojphlwHvqo=,tag:SGESOqD6m5h+d7ybfKVc8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
