apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZhDYKdFdp1YHEbp0dxLl/k/zQCs3JNGyKrOhdq5Uj+K+5rHDDoLv1g==,iv:JLoRhzXKo5HQ9SWUAgT/fdqp3liYVXXNzS8w03EYiFc=,tag:FHjtklQWyOkJDw2E8y5N1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N0plazJSejVLWitWUm5r
            WkVCK003Q0xkMWFUTGJUemlVdi9wazdTRWdFClJHTW55bTZoaHdxZVgzRmRjSm1p
            MHk2eWNsdXN5eUg5dk9welBMS29HczQKLS0tIG9EUFByVTJJQ0xyaXBQUjVDQTBY
            aFFpM1ptS1cyZUs0Uk9pcjYvTnJzK1kKRf472pF0WQJqQpEl9QzyPZbjJ06XAIam
            1a62wkhr3DnQbuHX16QNoYBS8uRSDWMOlVbp3UzcgsGzSnmRvkglNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T12:17:33Z"
    mac: ENC[AES256_GCM,data:c62YLlxZkf8SPusTQDGGWVn0YH73H5XK3A6t2HsLhDlcPS6gbnahZ4tMYVgbKkiDgkFtd3ync6/112jYi8SQJ1XkUI+Ta/gjFBPeNozrbEfvx8QCyX1nL3CaZkQyhNBLW0r500FLaIDnU/6zzsaBhEOh/qxIiFMBsF4jMC1WQ/o=,iv:VChH3HSXAGj3McPCNL9uSNTDPqlHgbsQRrCrRBAxp04=,tag:IHAmpjl1h4SrY++gbcUIqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
