apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:VHz01t1kHYPaHRGefnNJaNbaRSjffG0Wa7bsG7UUJieD8SsT0LLafw==,iv:upLRJyZheX1yJQhMdvqC++svKk+TZwhQnXU/f6cDm1w=,tag:Labmjjkr2d/BKrmKaklOoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa2ZyQ1M1REl3UXROQVpF
            a1pkWUsyOU5ZbTdMQU9jSzhNU0R4enFNZEU0CktjVGVIenJNWUFRRy9VdHVpdlJ5
            Z0V0TmtBSnUrcmhyYkkrWGI5TjMyMFEKLS0tIEs1UjlOTDJsTkFpMDN3K3p2dksz
            VlZYSnJuczZpbERzclhzN1ViclFmNjQKtN/WqbobwtJYf0FOcPVk6ip8uQNn/RfG
            vypOHyd0TRrMK6nLx0oWBMae6JeZaQ2SXvXMPe0pd8mwzVlchcMY1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:26:24Z"
    mac: ENC[AES256_GCM,data:+BwRjyYcgLAz/b134gP7VlQ9dmwK//thI6TDvJmIHHZGKKD4wZWwDYJi3YhiAUAQCHeGLMUulf6851qt/8eid2KawmYHoVY9YyokofSPSOEyRiW9SAI4BaZqv6sNlEk44rZVEx852ysnBFMmQ8UTQuBHQdR1CjPU3MvlP47iSQw=,iv:uMCVLGgxgUqn3IRzuKJpuIWWwbpaTfBoXgoTWb/K78o=,tag:r8F76YKPgRfoGg7vyd3amg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
