---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: grafana-secret
    template:
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASS }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
        TESLA_POSTGRES_USER: "{{ .TESLA_POSTGRES_USER }}"
        TESLA_POSTGRES_PASS: "{{ .TESLA_POSTGRES_PASS }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
