---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASS }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-teslamate-datasource
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: grafana-teslamate-datasource-secret
    template:
      engineVersion: v2
      data:
        datasource.yaml: |
          apiVersion: 1
          datasources:
            - name: TeslaMate
              type: grafana-postgresql-datasource
              uid: TeslaMate
              url: postgres17-rw.database.svc.cluster.local:5432
              user: "{{ .TESLA_POSTGRES_USER }}"
              jsonData:
                database: teslamate
                sslmode: "disable"
                maxOpenConns: 100
                maxIdleConns: 100
                maxIdleConnsAuto: true
                connMaxLifetime: 14400
                postgresVersion: 1700
                timescaledb: false
              secureJsonData:
                password: "{{ .TESLA_POSTGRES_PASS }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
