---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
 - ../../components/common
resources:
  - ./memos/ks.yaml
  - ./linkding/ks.yaml
  - ./spoolman/ks.yaml
  - ./searxng/ks.yaml
