---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  #- ./homepage/ks.yaml
  - ./linkding/ks.yaml
  - ./spoolman/ks.yaml
  #- ./atuin/ks.yaml
  - ./paperless/ks.yaml
  - ./obico/ks.yaml
  - ./mealie/ks.yaml
  - ./memos/ks.yaml
  - ./vikunja/ks.yaml
  - ./manyfold/ks.yaml
  - ./kite/ks.yaml
  - ./affine/ks.yaml