---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
 - ../../components/common
resources:
  - ./linkding/ks.yaml
  - ./spoolman/ks.yaml
  - ./atuin/ks.yaml
  - ./paperless/ks.yaml
  - ./obsidian-couchdb/ks.yaml
  - ./mealie/ks.yaml