# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:GM8B1q5zroWS0NJUQ3wDrBNL3Q8tOxM7bhKTQEjuM5oSIXg0enAY6ZmmrFYLNrn/79NvNzPxw8R5mZIdvkNH2wMPQvb1PMt6SzTZzaXakaNW2PLHbKF0B7S/riGq7bfSJzQROYxBHcLqv6l9MHUS+4zUvHBX/GhqQ/J84qcqCJmbTHqsm/blkuOGeBcBDUmufK5uEGCm+gsXeKbQ0fx4lpODcjfjfHN3o5EWRNciNLUgfDQc,iv:bcNFChCfBFdZPUcvEPzWIYq3tBPsrQgi7+R7+AXdRh0=,tag:5JkIJUNOxdLbaLG/e4BTLw==,type:str]
sops:
  age:
    - recipient: age15afcz4qr4nle0wjg8l3u32jn5jklu3yaek6yu7eepytczevs7d0qqym5gc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeDZVcURqOWFOUklxRUFM
        TnZxNU1EOHpKdWRHTnEvWVc1NEdKYzVIbWxFCnRkc01SMDFDYW1IRFB6bkgvVDVE
        QTRoNUwrWFJWZzBMSHJ1QSt5NWNSNEEKLS0tIHR6ei9xUW12Q3d1S1Nnd3dZM2U2
        Yk53UzlCV0tZNjNiTmFhU2d3ejhNOFUKzmVuDg3nG3X9siUclkKOHWD6Ivk7QQRI
        1zBo4tZKFTATnawWMSslIzZpdYTm3nGFEGHFJ93sQ0agIw22I7QEvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-02T04:16:57Z"
  mac: ENC[AES256_GCM,data:DnFMI5S9Tk6D6+p4pZ0h/UTEEREINHqlMex4g0ra9i9sNKZyev25WylBXreKRI13WR18cKPtj1I/VX3HNWYpS7NjynfJntXR2McKEnoYgrXqDHvhRUPFt4/fdY3256ltuQbNPVXA5QszWe2cKdzhcp+uTJ14SMCgBPZGw0FQsQw=,iv:XXN+iX1rbPDK23H4KjIgH6ruWr2vTNGZsAL6Cc5ZFDc=,tag:PzyqKCWnb/7wzWcOTbZsPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
