---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret soularr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.ini: |
          [Lidarr]
          api_key = {{ .LIDARR_API_KEY }}
          host_url = http://lidarr.media.svc.cluster.local:8686
          download_dir = /media/downloads/slskd/complete
          disable_sync = False

          [Slskd]
          api_key = noauth
          host_url = http://slskd.media:5030
          url_base = /
          download_dir = /media/downloads/slskd/complete
          delete_searches = False
          stalled_timeout = 3600
          remote_queue_timeout = 300

          [Release Settings]
          use_selected_lidarr_release = False
          use_most_common_tracknum = True
          allow_multi_disc = True
          accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
          skip_region_check = False
          accepted_formats = CD,Digital Media,Vinyl

          [Search Settings]
          search_timeout = 5000
          maximum_peer_queue = 50
          minimum_peer_upload_speed = 0
          minimum_filename_match_ratio = 0.8
          minimum_search_interval = 5
          allowed_filetypes = flac 24/192,flac 16/44.1,flac,mp3 320,mp3
          album_prepend_artist = False
          search_type = incrementing_page
          number_of_albums_to_grab = 10
          search_source = missing
          failed_import_denylist = True

          [Download Settings]
          download_filtering = True

          [Logging]
          level = INFO
          format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
          datefmt = %Y-%m-%dT%H:%M:%S%z
          log_to_file = True
  dataFrom:
    - find:
        name:
          regexp: ".*"
