---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret zigbee2mqtt-secret
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID }}"
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .MQTT_USERNAME }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: zigbee2mqtt
    - extract:
        key: /mqtt
