apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:VgDBlp7EtAOGNEpi11G2bKPpdopeXPArb5bOtzpgiAz/MKYA9rrAkaDN6FT1PqgPfDOm4D1XkvIe3MSRkJZn1FEIVh9DLQZP6Mcvlp+MtQJFxBBIPPcfmfz/lW6YnQ==,iv:6y888YSM7ED/7TE2XeFmJ7V/Mt6bhBiaDbzdgv+YcUY=,tag:oUBZ4QDfOqH1bi7YRsRLtg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZnLcPq1Kphu/,iv:dedlUVvI25Pi2NcicguhmRLJz6chhysdGeh0/nQxd6U=,tag:pmkpKnBePj6gfd1ua+kbzA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:6pTreAa+3gZ+hZja2s/kJ6NBpg==,iv:DqFtn7A1oPOQ6NEATr3JBSlPkoYPWKM/TofielY7KQY=,tag:D7o+1lK6bx887ADXEZkzeg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:hu/2vvi1anh+b+6HOAmHQ7/0lG7VzRT+MMfR3Z+Vu85DwY1K,iv:nTaDlUxcTHdzLCNijsAijn7QfzAQMVlt1qA1LndK2UM=,tag:efN3KT8Rh3kiR4+FLpsEhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wwn8kcfxfc2ak7pjxr4qxc3sjhrm6z2jus8swqkgmqzrzp8mdlsl5n3ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQWZrNGZHS085MEpoTFdE
            NjdWam9HdDNEZ3RxQ2k0dnR5YklaY1Rlb0VRCjR5R0dqMUp0RFBHWW1EdTRiWkhH
            N0ozYXZWQWI1QVVnc2I3ZWxtSDJOSG8KLS0tIFM4UnpLZU1jT0RuUm1SVkZ3Y3FJ
            a25ibHR0ZHZHVXF3L1dSNXN1dEhFVnMKKQjh/A8KKJ/Qq0F8wS5CzjlFWg3TyY/t
            EYMN2ZyE9cduoZbEGLhyZXmvKWVd8M8ohfGqjv06XOdK2628ZOtrIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T05:59:06Z"
    mac: ENC[AES256_GCM,data:HKUXjeVI6DP6u7FXcp1I29dblPltebF1Oatf7YYxjh4KDLvhln09+wZZeGiumYqublanQzQnGgOx93wX50SWS86QqTOvWnPj8yoJ3HL5cX/mN2P/4z9SXWcXZEBh7cLF7uC8T1bwYT/F6FJ3iYi3QrcKfe8T/+Zalvunho+qMQY=,iv:GqWuhioUSG3ppc/x+1j/Hu2/np8bCb9HvTEFP1jz+4Y=,tag:YoJXISGPwwbi0v3TWpsMbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
