apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:JxInW+I6w1594h3r,iv:P4CtE7owOSHJ/9pmS5GGYNkbNioL59gekzuqnoKGLxw=,tag:Bl7ccLCe3fP8cBcKakbZeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Tm5EbElVbkFPMm1Scmlv
            TElLTWVIcFVHc2QwK242WURJQXlQcHoyT0M4CkcvNXRqWmdOaURPblZIcHE2TEtB
            ZS80TVpnRVRVSlZJbUJEbkJ0VVRJYVEKLS0tIEpUeEVxOXlJeXRuN1dWVnEyTkla
            Mm1mWW5iVm9FbG5BZ3JRNldQOEhZU2cK7a47GKzD7T0u7Ec6GveASr6kKCWhuurt
            hP3kY8bdc8zKS2tTvJDqOdvecfUHp7V3b/+sRgBZc1gulFQ1FAFaJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T12:06:04Z"
    mac: ENC[AES256_GCM,data:PY63FF2JkqO7FGE+sJow7KbM62CBBZmL9diWsrbY2uQ79p7CNxoAcgXYf7mx8pJMr/u2tD4ZqkZzEuTu7DC6MFP8ZO2ZyOROdxsgra6Fy04t+jwf7hoHSmD1jl4N8KsbFdruaDDpIahkDZq4uWaVFFacHSeFtIsBgg4rB08Yspo=,iv:o7/FtH1kJ9fBZJqEMuKihcngmSMoqKOjWJp5F7OPCCI=,tag:Hn754AvNRNvPu3WzbkuRGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
