apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:vfh2IVgYBX158vX6L751m1UU7XpC+rU/e2TeAxrV4+o0Rsqn8djBKDOkxYVKJFivi3s2E+NMBBzarLOt46XaIKzQl/pGvtLPuFufdOGBkDTwxTRFcBS4fw2sZiZu9Q==,iv:WR2q9OfXnY7uQnK2kIYVKQnajskhIrASbMVjvxAx6vU=,tag:c4TvGrC8L/swqvz8bGSg9g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zhoJegoV3zHo,iv:kEZhUyyli8RhFq/JYvebwUHcZZSu3vzjvh6Ezt0oVZI=,tag:RRMgt2FYZxOCk4mF6HLUYg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IYZv8rEITTeRYPy/volrT+XY/w==,iv:zkdoq5hO0abw/4jEq10U3viyNTztgXTujI4pTGP4Zik=,tag:HoYiYPefQUmfzk74AHcECw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:qzV9vU1tENiQTzoPgwssLu3Huti8maok5AqHSBhmBm5tD1tc,iv:qrlsH+E0Zg4pBbDonqukyQ8PYMc0qrPpNiObhRFX/9c=,tag:G5rlp3neIaWT/hW/AzwhCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ0w0MWVIRHdyMDZhc1N5
            SDNzVWhoV1hOUS9iMGlYRkhDZ2dvNnNBL0hzCklPRnZacEFma2JSMFZweVlwWUsv
            MXViQ1ViR3JGeWZMK09EOXBrRytKdVkKLS0tIGxRZlp6RG9tODFMU2YrQ0dEQWY3
            dE1FVURXY2x3aWQxbUdOSGcwbFdjL3MKqTXZfhiLQ3nIncV25IAEtsVPuGMoDYws
            ggza3BQSUr2Mxgd0588yhO3R3T4wlj65zkaEFc3m4dBXaWSh4vLASw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T22:54:18Z"
    mac: ENC[AES256_GCM,data:xC72X2/myTI6HSNYvphbtgwZ6jTZ/CY3T/uKCEyzHKHgVSly89jxgB2ymhNk8tJ5vdl0oVH5K9vbpS8LsE0uJrM+s/sDkhhuaUeT2+Wv2GsIsd8vV9+HKRC0DWPq7MjDnTrFf6ui+3QptNfYURYTZEHs8a1AEpqnofyp1qBYxEs=,iv:w0A+JycCc3FybVQNHc6TYEGcOj0acmbJvw04sJyDXYY=,tag:CcrEgZddWcAzT5jd7Phxfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
