apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:zee4C3LZkru9sqf7,iv:eKQgTCCwnQ+S2Y8EYtTWC9NXLFg8s89MDTvM0AJ/MQU=,tag:LhC1OL/MZXqjVe/crw2vXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhR0FyY2I5blhGanQ0VWlB
            TTdlTjRZckFwSGZmanVtVHRYanlUaUlIMkh3CnBsdlFwYnhUc1dLYTVodjB6cE81
            amE5blJUZCtOYWh1NzdsSmpNaEs2c3MKLS0tIE9QRStldXlqT2FkYU1rOHNOOE1Y
            TXczdDQyd2JLbXR3UWF1b0RTNVFiUU0KczAirdwekG8nx2o+o+JwTgygFBeJtD3t
            vcR3UM6em7gL95H91RjBco9PxEJKxufTXfvbqHLUhGoQAzfBwwWMuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:26:23Z"
    mac: ENC[AES256_GCM,data:3jB/etnszPrBOR1pFg+0MtOn0kF3WlToxpCya8n8lnszpzgWOlu+ez7H0yXN2qkJSMEOscGfpVXG8tcceUm61xpftNBymMWgg+LLa41QuFBj9l35Q+85PuaGdfiYejUmPKX4MSNSh5VjN0eTBydEGoqkJFFKrvChhed4qXzifuo=,iv:FheHOMvxEvqknjQBVNwfb+oSia+q8gIymuFpmwIJ7EI=,tag:AgLxC/dM/pgPxStYLF119w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
