apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:2cHoLEKQ/5ZzlI6uqWGDxBtY/A==,iv:MVzEvOzO5vu+exYAuDO27eT0QH0bTu/5YV90bqNslKE=,tag:HROmkHGC+jJpXGkvQR33wQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+T7Up/8jDbrTxrV6OrCMQx22sm0xYeJrqDDGY+eK06/TWHJS,iv:+0r4xYxQuYNke5a+h1TcrP45gbEj7subSNYa2BBG9wg=,tag:AGKWnB7S7NCVPWQYuo9fpg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:AgPkF4yWOY+R,iv:ZpBoCz5TYohPbQ+Rrva9VUABZ7WMWucKOPot0WgMUiQ=,tag:FbAsDToDALHR1wbr2+ClzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK3NSUXo1MmV6MXpTWkts
            Q1ZCd2FyRm1uYlpWdFl3OFNVZk9SbjZsQ3p3Cnk1dnFYSXNDWWludVlybDNWSkVj
            MS9YTXBEcEJ6OTRRMmloWWlndGl4ZTQKLS0tIFJlS3JhbmVUOUxLMjl3UzV4cnpv
            aXA0RWVFMGJZalBzL2NzWkNCODlQWmMKuzTYw4zTSoB6beZLxRWCwzWilyHxhw0Q
            FYTf6WjOKcVAeurUtaVEnNWbGQDTFEjRz1RcnAz322j8BtMtcTVVZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:26:23Z"
    mac: ENC[AES256_GCM,data:vwrGMmouGRbJ5I+XfhlhEcwCTvKUvwZZlUtyr3UxRz24iuSuacySg0PAxVSYZGIOuoCNKWsq4ZOda3lqRDqQTC94+Saks/TTNb+P3n8rhfOTXr7UfRz1gG0UXpgRXCcmfWpt6M/CjWOP4cRO9SLUtX8c1ibABPm5v3gxyK61nSg=,iv:RhbszOhB5nWlME5L+63Rc86VQvHbIFOOCE2/a5tKvtM=,tag:gN4WRS5me+ofhpvq2lU1TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
