---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: network-ups-tools
  namespace: observability
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controllers:
      network-ups-tools:
        strategy: RollingUpdate
        pod:
          annotations:
            configmap.reloader.stakater.com/reload: network-ups-tools-config
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
            cyberpower.feature.node.kubernetes.io/ups: "true"

        containers:
          network-ups-tools:
            image:
              repository: ghcr.io/jr0dd/network-ups-tools
              tag: v2.8.3@sha256:9f8e14d155c6ef05940cee6f8861e259e951eb11750aeddd02539d986dac1ca0
            env:
              TZ: Australia/Sydney
            securityContext:
              privileged: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true


    service:
      # Network UPS Tools service
      network-ups-tools:
        controller: network-ups-tools
        type: LoadBalancer
        annotations:
          coredns.io/hostname: nut.narden.au
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 3493
            protocol: TCP

    persistence:
      config:
        type: configMap
        name: network-ups-tools
        defaultMode: 0444
        globalMounts:
          - path: /etc/nut
      ups:
        type: hostPath
        #hostPath: /dev/bus/usb/002/001
        hostPath: /dev/bus/usb/001/002
        globalMounts:
          - path: /dev/bus/usb/001/001
            readOnly: false

    configMaps:
      config:
        enabled: true
        data:
          nut.conf: |-
            MODE=netserver
          upsd.conf: |-
            MAXAGE 20
            LISTEN 0.0.0.0
            #LISTEN ::
          upsd.users: |-
            [upsmon]
              password  = "nNpkeox7$upSQeKfekKQ"
              actions = SET
              instcmds = ALL
              upsmon master
          ups.conf: |-
            [kubernetes]
              driver = usbhid-ups
              port = auto
              desc = "Cyber Power System, Inc. UPS"
              pollinterval = 10
          upsmon.conf: |-
            MONITOR kubernetes@localhost:3493 1 upsmon "nNpkeox7$upSQeKfekKQ" master
            SHUTDOWNCMD "/sbin/shutdown -h +0"
            POWERDOWNFLAG /etc/killpower
            POLLFREQ 15
            POLLFREQALERT 5
            HOSTSYNC 15