---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nut-exporter-server
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: nut-exporter
    app.kubernetes.io/name: nut-exporter
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nut-exporter
      app.kubernetes.io/name: nut-exporter
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http                # must match the Service port name
      path: /ups_metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 30s