---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nut-exporter-server
  namespace: observability
  labels:
    app.kubernetes.io/name: nut-exporter
    app.kubernetes.io/instance: nut-exporter
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nut-exporter
      app.kubernetes.io/instance: nut-exporter
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http
      path: /ups_metrics
      scheme: http
      interval: 15s
      scrapeTimeout: 10s
      metricRelabelings:
        # Generic rename: network_ups_tools_* → ups_*
        - sourceLabels: [__name__]
          regex: network_ups_tools_(.*)
          targetLabel: __name__
          replacement: ups_${1}

        # Keep ups label consistent
        - sourceLabels: [ups]
          targetLabel: ups
          replacement: cyberpower

        # Remap the UPS load metric
        - sourceLabels: [__name__]
          regex: ups_ups_load
          targetLabel: __name__
          replacement: ups_output_percent_load

        # Remap battery runtime for Grafana dashboard
        - sourceLabels: [__name__]
          regex: ups_battery_runtime
          targetLabel: __name__
          replacement: ups_battery_runtime_seconds
