---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret affine-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        # Database
        REDIS_SERVER_HOST: dragonfly.storage.svc.cluster.local
        DATABASE_URL: "postgresql://{{ .AFFINE_POSTGRES_USER }}:{{ .AFFINE_POSTGRES_PASS }}@postgres17-rw.database.svc.cluster.local:5432/affine"
        INIT_POSTGRES_DBNAME: affine
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AFFINE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AFFINE_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_ENCODING: UTF8
        # App
        AFFINE_SERVER_HTTPS: "true"
        AFFINE_SERVER_HOST: affine.narden.au
  dataFrom:
    - find:
        name:
          regexp: ".*"
