---

apiVersion: 1

datasources:
  - name: TeslaMate
    type: postgres
    uid: teslamate
    access: proxy
    url: postgres17-rw.database.svc.cluster.local:5432
    user: {{ .TESLA_POSTGRES_USER }}
    jsonData:
      database: teslamate
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: false
    secureJsonData:
      password: "{{ .TESLA_POSTGRES_PASS }}"