---

apiVersion: 1

datasources:
  - name: teslamate
    type: postgres
    access: proxy
    isDefault: false

    url: postgres17-rw.database.svc.cluster.local:5432
    database: teslamate
    user: ${DATABASE_USER}

    secureJsonData:
      password: ${DATABASE_PASS}

    jsonData:
      postgresVersion: 1700
      sslmode: disable
