---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret slskd-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
