---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.8.1
  url: oci://mirror.gcr.io/envoyproxy/gateway-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  interval: 1h
  values:
    crds:
      enabled: false
    config:
      envoyGateway:
        provider:
          type: Kubernetes
          kubernetes:
            deploy:
              type: GatewayNamespace
    global:
      images:
        envoyGateway:
          image: mirror.gcr.io/envoyproxy/gateway-dev:latest@sha256:49852aed7613c8670302a6a64ca3fb5533c8de8584e91362243fa80312bc1291
