---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret memos-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_URL: "postgres://{{ .MEMOS_POSTGRES_USER }}:{{ .MEMOS_POSTGRES_PASS }}@postgres17-rw.database/memos?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: memos
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .MEMOS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .MEMOS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /memos
    - extract:
        key: /cloudnative-pg
