---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        # S3
        MINIO_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        MINIO_SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
  data:
    - secretKey: MINIO_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 9a0d873b-8d70-46f2-8c92-6dfaf390821e
        property: access_key
    - secretKey: MINIO_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 9a0d873b-8d70-46f2-8c92-6dfaf390821e
        property: secret_key
    - secretKey: POSTGRES_SUPER_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9a0d873b-8d70-46f2-8c92-6dfaf390821e
        property: username
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9a0d873b-8d70-46f2-8c92-6dfaf390821e
        property: password
