apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:WPe66Zy/70GP/VgODj7/GR00,iv:UmJbRGfUKOeIpN6W2JePoLrH7gZ7BfKGylhjPjODljY=,tag:xpB5Psd7iAxNKODZiMpycw==,type:str]
    password: ENC[AES256_GCM,data:EAgqxQGDK+02hfRH28ngMZ8A,iv:+9N8lDpu9shiZ7bjkRod2XcDF5LDO7QqFhP3qg0R/o0=,tag:g+GyJ+ashLgTmBwCnwhGgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcnp2UjlXY1BLUlc4di9l
            QmhlTHBSNTZ3TkFubHkrQXdaUm9ybG5XSmdvCkJsUUlBUHQ4TGpweXIwamhiNkZX
            eHRaRDFkUGloRmM5eTVtY2FOQTMrOUEKLS0tIDBTVmc1dG91UFhueXJIQ2dEQXFx
            N1ZCVnFKaHorTkJNbyt6aEtCa053eE0KoixfOTbY8ZqUpGBC6h9nIJznFRhnu4Q2
            H4xt+gQiZ5KJnixgv95sK4Xmz3FGQq/UxCoydV9AN5GocNGDNmHfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-28T09:59:55Z"
    mac: ENC[AES256_GCM,data:PDCk9aJ6DqBNBPV7H+lC7yZLp0SaLjEN7xO8qIy3wXOD5UZrr1+Z54z9thUufAVM9HYhwuM3DEMi3b1W7VRegKSc1pU5H5x8XcDHUqSJBVzKlfLf2SRKFhuSeAAfhk+PhDmrTXdfCauSwnQBusmSmIAXzrY00VOseCFXAOs720Y=,iv:zmyAFMvpgSBO6qzrioudx4jgTmt+AOc4NqFH1Ov9dkg=,tag:/7HGj8dXcrsjC6c4DoAYWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
