iapiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: flux-system
type: Opaque
Data:
    INIT_POSTGRES_DBNAME: home_assistant
    INIT_POSTGRES_HOST: postgres16-rw.databases.svc.cluster.local
    INIT_POSTGRES_USER: postgres_user
    INIT_POSTGRES_PASS: postgres_pass
    INIT_POSTGRES_SUPER_PASS: postgres_superpass
    HASS_ELEVATION: 777
    HASS_LATITUDE: -35.433333
    HASS_LONGITUDE: 149.216667
    HASS_POSTGRES_URL: postgresql://postgres_user:postgres_pass@postgres16-rw.databases.svc.cluster.local/home_assistant
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SW1zUkNyQlVMUlZLenRL
            MWtoeVVwbnNBandsQkRFK2RZdlk0YXRVN0RzClp4VlczblhCd3Y4MG5kRHk1K255
            elQ5WEg1VVI3SHlwOGhaZnNOU0pRNW8KLS0tIFYyczVUc1N0TXVlckU3bkZRWERB
            bXNpNUFFb0JGcEptZThKYUtqOWtRQ2cK/3WvT/FXdCWKcLu3cMGILV/8TBQ+zSXX
            iJu6PSzUqa1MTbReXrYY29wjw41/S50z4FZnaup+MFU/LC38InjgaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-28T10:48:37Z"
    mac: ENC[AES256_GCM,data:HOH3vPXpvs83Q8zIqLqQlNDyFaE540Bj01jdNuC8y3ulu3HKs5CO5bTAC7o13ueL8L0LqvfnbShOi/uagBtPujcpebJMeREubhKhfWHFj3mIKqphnwCgfeP2tnGoH2SCKZ5474i4rXTCU+eSTjb9g/P4PFR26CLnGbocLzZD5vQ=,iv:kZ9bsthIEIfqyk2KPSYqV98V70HlslmujLYH3S9cwkU=,tag:16MJ2Yl0HSpye48FjRf97Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
