apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:vjXv/jKlV6Vxsy/5j/c=,iv:kJPfn7Al/eXdDuYriwcLTFgvitW2/uhtCk4Mut+YPv0=,tag:B8nLxzoFwx0dhNkJyUNYpw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:TqTKZRPxIs6BEGWcdOMEUL/F+lnmYQ0HOLrQkBjcP3UytRJ/pj34yQ==,iv:yaG78nm1XcFHUXVAd+TVzquyulZj8zs23i/qnDlG76g=,tag:wF4ZG5GM855xt2QCeUXPcA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:tGEu9exoD2fzGkqwWQ==,iv:H4uy3RSe1cvOtI3qSWw0PBJ7KjW7cWqsV3JCb4Mph8w=,tag:CcYTvUu6xE1wGZaDNkU86Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:wNfJriaK/GzFQ5oLoA==,iv:9TQaHvYZ8YY81jhWBb9zMlbiFpspK4zzjRth4GtUqs8=,tag:R0nwOrFoMmMr7afvQ3TJ0Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:b6zl/NcW5/9agDM9Zncu0nUV,iv:975SWLcS0cboVka5EHHX6MFZEgw4q7XvtcC778I/H1Q=,tag:E+Cla6Kjk3jsclr0oPY0Ew==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:tZiZ,iv:OyGZ3i0WlfocHhkr/F9GjbTCgv0olgK0CGw4IZ6Of5s=,tag:4Fah7a9wRqvoAbNWe7hjJQ==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:JpQh6jSCZ5I+ZA==,iv:jh4Y7tyQPcv0aReyh3Db/frvUfJG12I8QF3msRjPxrg=,tag:nLjJk6KoGHG4oUpRIvv5AQ==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:AyeIQtTYfwJa0g==,iv:32+W9bguPsWM6IbZw2KQtanfuVIwCM/mu84g/MedRdA=,tag:DJ/rElM+/GsYyw6kbCLymg==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:X3TfjLo9vSpS/JhVRwkAJVs+sW9Zvj7HlrsOC/npjGnml6Gl+0pY4R71f0dcZ/zk7SPNn97S7tnZ9SeW2XyFitahqjKPJKRBgk2UWDi4Zg3U9HoTWn7PxNo9j6G/b3Jm,iv:xyOhCuXoeWualTBAsVGmVhfxMR/S9wl0lfMa1Opdmx4=,tag:nlfux2HLWWXmObN5DXffLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV1YvQ011dVo0MlR6SFFL
            S1BhY0JxbnFoL1NMRHF6VkxZMmk1M3lZV1hJCldUbE1WMFdSVVZyMzZhNm5ST3cw
            dkpreWNaUnliWGUrV3A2NkxzajdWOUEKLS0tIG0yOW9ka01zVWxESWFQM1ZkNXIv
            K0hMdVpDZXhHaGcwWFovR01jNWluazQKFxNe5QOjjnZ+CFYHvrCuzgetI//eTBnv
            JEXO+BGgkheEZVFgXwuqkUtuijHR+JtBWB/2wwLd2a1ljXOYaXbYmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T12:04:53Z"
    mac: ENC[AES256_GCM,data:4/HCBzLX4kg6GK1B8Y+n+O0LY49208Kirytvk30Zpi+QgdaUhtVg8p2oVpJ3tIUbXrUE5v7pHaf+0r0rQieJY1/SO99pYk1wcmrT4ybEQrhurhX95hl5b8BQHsSmZeychGMI28asOoMOU223tksLPvEztiqDbMLLnhwYlJJp7IE=,iv:gHCj34+pF7pkIDPdELTqFxHZKtFL0DL8R+GOZglePB8=,tag:gK5EAe8BaCBiTXBWlAw93g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
