apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home-automation
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ScI8aXjEz8sT8crUnvM=,iv:H8aEJO0M/yMtLo6GU+XqJqIYRew/0GEz5l4VbutBODw=,tag:xQiiaXPTLIMVOWcma/h8SQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9C5fRDH6x0gnSv6QzYHAoWH3Kcavjt5AlymABkvIUdlzB98rI0kTZXA=,iv:2vJVYy4TtESisfeb0p9ATyhsieqOUXlQhEcNnNiVrao=,tag:gBzDa0a60pJKWzLe0702Dw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:aTNizF60Q5+vvOYQaQ==,iv:QU4CG8TRXMW0Y7eYmLAIfUZmBg+1ptuFJqUvDyjPfxM=,tag:IJm/z98/S94VeLLZy0u0og==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7ZNdfLW+vzztYznAQQ==,iv:tZEELCjj6sHqwzHvx7NmHIEhmCrUaMYsxXz5V8SPLLY=,tag:kFpPj+GDKDYyF2bh9iucwA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sk10XEr8cWkqgsIEnpHWDIw+,iv:yswyGyLR6DeYt2ik15BjywG2qE/NyegrjU1U608P/OU=,tag:I6lTd81Axzop8MWJctfmKg==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:CFow,iv:BdbR+WzF/Whgrzzu2MamurCq2V4/ErXJGDWs6Cy8yCw=,tag:wrjEu9FwVcsmfsyZygzaMQ==,type:int]
    HASS_LATITUDE: ENC[AES256_GCM,data:sAW59vPSOM5arw==,iv:OWYhppGM0cQDz8Iw4mwZTNhcsVrbFojAUMPEgy7EtmA=,tag:eV487l0kGFIzohVZBXAR5w==,type:float]
    HASS_LONGITUDE: ENC[AES256_GCM,data:Tc1XKjJdWIypVQ==,iv:3SUMUGJDLp3/kYYi2mYMi4RJa0AV6h4aX8CFtWZlOKM=,tag:8wQbirmfBbPE/NoMtUF1GA==,type:float]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:QzK9WMTZ4pSw7mZ75eYaW4KQoHMtXuJPAI+NHM6fFQpC2SvTyvBbRJ1f3ktS2qz4nOm8MX90Dyw9TzJFmxCg0e6rcIa24HJI7pFvT9TcScE3zm4lLO75R9MGUF4lUREUow==,iv:wVSlhmXJ9whaZGVP5Mik4nbuqh3EYmGqE9Gmm+R9d20=,tag:ctrgDHwqy2DfnGLrH5efDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQU9YUjQ4TGhpa3FXUVAw
            ZFhvZGdtVVIzMmJxa0lVRytKaXRXYVNRZGkwClpLMEdDZitRNlpXdHFBQ1BmNjdI
            UmgwVkdWM241NEpPbHhWTlhGYVRKblEKLS0tIGc2SlR5SFNveTFOQjBPQS9rV25J
            dmZXVDlQdGNENXpFUjd0T2JoTkRzMkUKJwkjfB/G/eaEU7zLKKg0LPYSaZAkvuBA
            7yANYU9lwEuxSRDfc7eF108I01Bd6lRp3TFi67Gqf7GHrruLCrJPUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-28T10:40:13Z"
    mac: ENC[AES256_GCM,data:6lkqRKzLvIxsCMf42nYDLh/76jOUKEGBGMn/m7xSLYLxqmzPvDZ/kEYmY3LB3YPEJlXOGmy2DFw4oELTepTKFjZX+x8l9mfIX6ZSzD7ehSflrnG86LHYhXaNL9+u/9YhBurmJILljDUC/DJSdAQZmUjBdZ1UPVpRWIBeGTDRZho=,iv:fZBapOSwuSOf7qdNvVHO5XDliehzW8WENgX0z++EDhs=,tag:9a4CP/xpDLmCUNYldi0cnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
