---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bloghugo
spec:
  interval: 15m
  chart:
    spec:
      interval: 15m
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      bloghugo:
        containers:
          app:
            image:
              repository: ghcr.io/philgood/bloghugo
              tag: latest
            resources:
              requests:
                cpu: 5m
                memory: 100M
              limits:
                memory: 100M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &app blog.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *app
