apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:qlObzz1eYuG30KokfjbCr1JZtsUNojYO5FL3V34DHJyeNlJe,iv:ZgVj5Fgm9JG0XYMLfrBCoX8S8Jz8BYGXf79IlfdOiA4=,tag:2QglMN/8MDxK6c5jpD26og==,type:str]
    credentials.json: ENC[AES256_GCM,data:h/5Qb67XxXz7yuVz5N0r852WOsOTkwf9XewTMglNg9g9Lyu83219hETfhQc4NMAWf2msVAChLN/Vwwf5dWEs5nC/Jsf+pB7dJXCI8VWpfwIZzqYrOqR65vGjAmPdtNB9G5k5J9upl9CZOs3Fz5ViaRo5P+6eh+6dEtcgH2v5yaYjUKHKnt1/FL8PJF8Y3Dy4Uzu3CAtHi1NQN84oGCpex/1MzEHwz3Wsv5antrv7zw==,iv:U4JD77dDZ20hT7TLCOiVbWzt2V2DgESBeFq5fo7jzVE=,tag:ltrRhx2Ih1tTRdUMgMJfVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caj9cj4p8cw959s0kdsvlhswq2hrp2y70qhg8v8n9dd82dzffdks4druav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTkZwTWJUY29jWDZVMHdM
            VlM5QUkwM0tUT21YSThXb2N0cXBvY2lpaGhzCldxdEI3NDlOUGxEKy9hQTgyczBn
            OFJ0SW5wYlRDbkJscE12eEtOOFRkM2MKLS0tIFRoZy9TbXlJNjJDa0NTSWtuaTdS
            WXNTcS9YOVo5WHVpS1BGM1R4Tyt3ejQKC+rogVjfvRHPUogXirvpb1SmK2B778Hn
            WN+JEi7UmIsWIZpiVyp23G7DmMd5RSvPxsWS2IGYc+OTnbda0xuzug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T11:26:24Z"
    mac: ENC[AES256_GCM,data:2mG1O2X2VemkY5FBm9Xz1PugvqxU6lPpDtXTH0bgnN/rP1v3fpfZjjDJHVeDq7BLlkcY4xnKghrGSqNPOxWFRnooyi24kYCWZgs8+IhfTGNysuWchyxiQ7dM7u2IswflFopEt8kpwbNfJ67LMM474lv5+l+QWPB9cFyGcDqph9w=,iv:poeBt3/0C3VaQnPFeNudiIe4904pK6f2+GUmdBB8gi4=,tag:vdx6XRfTLwkaxl+xoekVGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
