apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:1GPwp8ovoGr36TqutT2mhWl6GINhgcEmgdYmUhK0Ink=,iv:RSo7fOnOezjeVjHuLh4bbaG5OAdX+tEcPZ1CvrizwIs=,tag:I4AO6C/WnUiuculVtYEBDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYM0Y2M25VZ0hFMHl5eFA1
            N1hOZCtUODRWMGNENFhOTjliU2pIS3hjVm1VCk5zdExrZG9lK2ZLeExaSFZ1R2x0
            Wlo1aUhUSFpLYURnelFLYUFOMStWWjQKLS0tIG8vNjN4UVZsK01VR2w0SzVTUW1u
            bDJzZ3V1dTg0TGN0bzhUY0d1OXdCcTgKjiitzoZHi0wz1e4tSWPVfSqSxRKpIUk/
            NtcBNnoZTEAsTTEnJEVJOa64uTLJvcoo1m4e8MnPjRMdgIf0irekeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T10:53:35Z"
    mac: ENC[AES256_GCM,data:Hwa6A3jm6CNdxfE7FTmWD1Hgal7AZsIOisRfc7eL7GvrayCdx1W+L2F0hBAFCXuyELbgFQ1osqMOaT6Z2U4DQZvxFpqNCpYH6RLj3Qw3kcjsbzCz0X/T7LFo0y56pWoxc9wt+VIzu5YapMIHNKbz5oVCkSsSEvr0dpI6AHNijrU=,iv:ptLikyFwik9Y1H/cKJJV6m8pYt4DmKmpZgz24wGgMuQ=,tag:UrCOxgJn+aLB5wQnRmqNCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
