apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:0mPPKHj+AITw5e/p7zO2BUlkqQ8FXIKMhTQ4cYZFFsM=,iv:39mFdvuKB5sCO5DO7Oa6sm1EffXfXIxY6SztzTlja8Y=,tag:XTEv+GbGzliFePvgcf0jew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZk9qcVA0Qkh4ZFlJdmNS
            czM5SVVvQjZhRy9naE9JcHJzNnUvNGV5elZRCjk2L2JpL3FueUFHMmR0MnpLaFJG
            K2poWTdxd2JKL0JHaC9qK1Ard0NzRVUKLS0tIE1mMTBmWGJZRENzOXBHaC9jM3Fa
            aktnRmw0aysreTBVNG9DVWxZRTI1NFEKIXiqZ9O46wLB9pyFA49mVAK/nwF1J1fw
            k5pGUfh1xK5/4DMHt9dSL8Na5xAy6Zs7Dj+0uRncX0iGxRXqvtpPxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T04:31:44Z"
    mac: ENC[AES256_GCM,data:JmImdzHCqWebrdHEdoDEBVRrwpCoMDvQXFcvkV+oiT4XSd8akUd+BwNDBwP6O0eO0emVLI1ciZ4KsTuASutvWfvgsav6RPEREJhwVuhbSABPcRsv2KEmLxHvlpTaUJxaD0/R1psz+b6xo5ArCJtszyj2bVxWl8r7SNqGsLwfwEs=,iv:DEz1NmV3anew2Vcg2IfCC4bydfq2oy5vGM5kkoPVu6k=,tag:e+HWHLoQPM54QbNkuB3bTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
