apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:okn3YVsmY9pXNEAvDRjWcwiQa6PEF+K87ijk2Jk8XSU=,iv:+qbYBCblJw5F80YFzNvVrzNM4R9G8QtD4Mui2uuvY34=,tag:T875lBE8ylP4n7pCvXo+pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSHN5UEhRQzlnMkY0cjlq
            dnI2V0thWWk4YzRNbWx0cnV4VmNoRU5CU0NFCkU1N3A1amNTbXJMVFBEKzZiUlRR
            WEEyQXlUWncxaVNXZ09RT3h4S3cxV0kKLS0tIE5pMTBtNExSSmJ4MUowQWlkRGFj
            cXladEpZYWpTS3Q0dk5jblVKLytvZ28KdRlGkLRiAY4MU/w0btuAZ72wVSP/DVlA
            wMrHaZpXkkRsPHaqZKVG2BeJZHsmy/JrOJ2Jw25vwJMLQeusG3NNUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T11:00:46Z"
    mac: ENC[AES256_GCM,data:0fvPbQAHy7ZTo4TYR8stkmw9oivG6YQAufUxRDftEMF7KigH+99qnr/+vz1bWeLnS8qMqU5Te/ZdOvX66Sjuq7IKiJRWCsv5Rwex/MVB6HhT/uijQHj9jyRYSIAZ1iZDylukVVecAAIYfCuzID2Ehi7LZHl3T4EZhk2jAcjQ4VY=,iv:YIzJ49RCBNs+h+OPGubN3I9OyAqt+vJlZIs6cPo43UM=,tag:mJeZ3ot7FNwDpLHt6/s96A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
