---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret mealie-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: &dbUser "{{ .INIT_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .INIT_POSTGRES_PASS }}"
        POSTGRES_SERVER: &dbHost postgres17-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "{{ .INIT_POSTGRES_DBNAME }}"
        DB_ENGINE: "postgres"
        # Postgres Init
        INIT_POSTGRES_DBNAME: mealie
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Base Values
        BASE_URL: https://mealie.narden.au
        ALLOW_SIGNUP: "false"
        AUTO_BACKUP_ENABLED: "true"
        API_DOCS: "false"
        TZ: Australia/Sydney
        WORKERS_PER_CORE: "1"
        MAX_WORKERS: "1"
        WEB_CONCURRENCY: "1"
  dataFrom:
    - extract:
        key: /mealie
    - extract:
        key: /cloudnative-pg