---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret mosquitto-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        username: "{{ .MQTT_USERNAME }}"
        password: "{{ .MQTT_PASSWORD }}"
        mosquitto_pwd: |
          {{ .MQTT_USERNAME }}:{{ .MQTT_PASSWORD }}
  dataFrom:
  - find:
      name:
        regexp: ".*"
