---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        # Media
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_SEERR_TOKEN: "{{ .JELLYSEERR_API_KEY }}"
        # Home Automation
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HA_TOKEN }}"
        # Observability
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
        # Storage
        HOMEPAGE_VAR_KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  dataFrom:
    - extract:
        key: /sonarr
    - extract:
        key: /radarr
    - extract:
        key: /prowlarr
    - extract:
        key: /jellyseerr
    - extract:
        key: /home-assistant
    - extract:
        key: /grafana
    - extract:
        key: /cloudnative-pg
