---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app network-ups-tools
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/observability/network-ups-tools/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
  patches:
  - target:
      kind: HelmRelease
      name: network-ups-tools
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: network-ups-tools
      spec:
        values:
          controllers:
            network-ups-tools:
              pod:
                nodeSelector:
                  ups.feature.node.kubernetes.io/tripplite: "true"