---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  path: ./kubernetes/apps/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: flux-system
spec:
  targetNamespace: rook-ceph
  dependsOn:
    - name: rook-ceph
  path: ./kubernetes/apps/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  wait: true
  postBuild:
    substitute:
      APP: rook
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-addons
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/rook-ceph/rook-ceph/add-ons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
