apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:3+juMzl1/YpEufj1XAOQMxjyNkg6jH7DpTe71Qhj/QlCj4/H94UHMg==,iv:g19PFxylFN5yhu02jV2Fm+xy5jBJZoXeHMDn08qO9pc=,tag:cUoEmD+7mkczkdVoYfDBew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY3BnZk9zTW05ZW93NjJJ
            eVJ4Q1RVMWFHczdwZDFYT3ZQaUc4LzFsWkg4CjZZSnhucUI0M2tHS0pvT1NzMG1v
            Y1pPN3VmVldMYUVhVkZFQTQxM2IwNkUKLS0tIGsrZDl2enFWNUI5K2RPZVVxQ3pV
            RkE2TjZkK3hSVk1vSGptNFZNNExUL00KrSzdRibmgvPJ6JCzn47XdE3L2pKyWmxE
            AR2rAuLOE5+IotsXDX8OtHdiZQ+wXdR9Dhygy/DP+kUwpnj8EuoPvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-19T09:09:02Z"
    mac: ENC[AES256_GCM,data:ls2eqd6g16rewvoH7EenkbG880SiqztYCKacvoD5SzWKgA2m1FXI6bJ99nBIJ2/LA+r8jevIfVPboerc+vURBugSIuHueVmCNZwByPvFBdgGrhKtINgbNiOjE9pVJrHWgt8NbnxnHteNUUcnDN36ti1jJ2Sv9jiWMMTCIYhpI7M=,iv:t8a8GiNH8n8/pbNnoSQ2h442V1cQ6X8aSiAkjMj+vyU=,tag:TLjnjGDfOjEKbh/UcmhuHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
