apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:aRIg84UyA4ZwSTxMLSi2nmHtdwGzlyoacgGAGfIad3p64ud46ITPqw==,iv:Ck06wsOJV0zpD0YHTpVzEqh9q7D+qcCWsFkVbXdGy6E=,tag:3/TRPG35/sz0bVulsJ8D0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVXlGaHIyRk9hcEl4Nzdu
            VS94c3hOdDhmd2ZzMGFBWGZ4eEVQTXpaMFRZCkp2c09aTnlrNjdUZTU1NkZqOTBr
            dTE2QmQ4Q0gyZy9xdW5pWkJtWTZtTVEKLS0tIGlERDNud1ZrYzh4d0ZEQnk0V0Jh
            ZXNIRCtHZTExQUVyajlwd1dMR09GbG8KXM4x2A+EFL+mMm8PbLqi1MRvo3dZZE4S
            so+Cl7EetI3ey26SNUrAATl85/rGXjOdcmjV37Cz6SxZ+xehVY5u4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T04:31:44Z"
    mac: ENC[AES256_GCM,data:nxzY6uADM3B5h+spCF898tQNQA8mwnXU20dX+oYBRGknSckfmwi6f+ybIPmhcB4APTpTyl9MEbvIL5npMzpWqSyi19tyqzoxrkd0rTa/wUAdzXTO3CpRGvq3PJLXaTCMZvvwLH957LIZumvF7gOZcMLsOZBBCmwf5cQyE/mSXdM=,iv:tivTWhnGl6Ryox+ZUStCjtIB2TsEroL3H8zK3/mDZXg=,tag:ubY0b/0SJnuGyRAJjOB90w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
