apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:oOf5HDeU6xmx8AMA3krPDC547rkLGdz7DFk+Mk/0/a/HFKvHN65nMQ==,iv:02T47O3X/Nk/7AuMzIoHb21tVcori1RecYSgNCIrHIQ=,tag:kwXa1b0qrxfSC5nAKu4sqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y7uxdzj7a5jdsdc2au7q3av6fj2ksg2dxr2lwkzyzelwnk5z2akqlm9cgz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQWpQNmcvQ2FUZjNOODhi
            UFA3TmpvK2g5WHQ4TnN4T0doa1p3ZEtWYW00CmNkMndYRVNwcEppc2h3bnBsSlo0
            UXJqdzVQR05lNmZTNlRGUnNtTlZ2ckEKLS0tIGVpbGdocmZHdXZQclZEUnJ0SklW
            d3FhYzZOMFQwQUV1NjFMMmM3QUJGaVkK4KPDlEinWsuEljQtpCQiWDqOT0NKL0Py
            xrRXzMg/28uQqtfHFHOaOFWUBodPcnFi/2S0MXVpwaCRa20u3d2K+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-18T12:17:34Z"
    mac: ENC[AES256_GCM,data:A3T1hicxrV/NGnNAIMrEGNeWgwXOcyM9npwXLQ8L+P1KNiysKvudlFWd4rXHMD1K7zj4g9S0ctQqP/89e0CFiBuNSOYc6HjgyXOARBnj4xIz1BJXntsLL+4cuGO9L7YKOQceR6lbiAIApR9Z7JKDmqSanzAXkRlu85yseryNtM0=,iv:/j3GlZbhuCrDAvr9eY2RkKmvvIIf/Z3QujJFxh+dXYk=,tag:Jx1mENqxsZuzVTj9kssG4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
