---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret navidrome-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        ND_INITIALADMINPASSWORD: "{{ .NAVIDROME_ADMIN_PASSWORD }}"
        ND_LASTFM_APIKEY: "{{ .NAVIDROME_LASTFM_APIKEY }}"
        ND_LASTFM_SECRET: "{{ .NAVIDROME_LASTFM_SECRET }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
