---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret pocket-id-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        # Postgres init
        INIT_POSTGRES_DBNAME: pocket_id
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POCKET_ID_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POCKET_ID_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        DB_CONNECTION_STRING: "postgres://{{ .POCKET_ID_POSTGRES_USER }}:{{ .POCKET_ID_POSTGRES_PASS }}@postgres17-rw.database.svc.cluster.local:5432/pocket_id?sslmode=disable"
        ENCRYPTION_KEY: "{{ .POCKET_ID_ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .POCKET_ID_MAXMIND_LICENSE_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: ".*"
