---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: teslamate-postgres
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  datasource:
    name: teslamate
    type: postgres
    access: proxy
    url: postgres17-rw.database.svc.cluster.local:5432
    database: teslamate
    jsonData:
      postgresVersion: 1700
      sslmode: disable
  valuesFrom:
    - targetPath: "user"
      valueFrom:
        secretKeyRef:
          name: teslamate-secret
          key: DATABASE_USER
    - targetPath: "secureJsonData.password"
      valueFrom:
        secretKeyRef:
          name: teslamate-secret
          key: DATABASE_PASS

