---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: teslamate-postgres
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  datasource:
    name: TeslaMate
    type: postgres
    access: proxy
    url: ""            
    database: ""       
    user: ""           
    jsonData:
      postgresVersion: 1700
      sslmode: disable
    secureJsonData: {} 

  valuesFrom:
    - targetPath: "url"
      valueFrom:
        secretKeyRef:
          name: teslamate-secret
          key: DATABASE_HOST

    - targetPath: "database"
      valueFrom:
        secretKeyRef:
          name: teslamate-secret
          key: DATABASE_NAME

    - targetPath: "user"
      valueFrom:
        secretKeyRef:
          name: teslamate-secret
          key: DATABASE_USER

    - targetPath: "secureJsonData.password"
      valueFrom:
        secretKeyRef:
          name: teslamate-secret
          key: DATABASE_PASS

